from rbac.forms.base import BaseModelForm
from rbac.models import Menu, Permission
from django import forms
from django.utils.safestring import mark_safe

icon_choice = [
    ('fa-cog', mark_safe('<i class="fa fa-cog" aria-hidden="true"></i>')),
    ('fa-cogs', mark_safe('<i class="fa fa-cogs" aria-hidden="true"></i>')),
    ('fa-weibo', mark_safe('<i class="fa fa-weibo" aria-hidden="true"></i>')),
    ('fa-weixin', mark_safe('<i class="fa fa-weixin" aria-hidden="true"></i>')),
    ('fa-tencent-weibo', mark_safe('<i class="fa fa-tencent-weibo" aria-hidden="true"></i>')),
    ('fa-address-book', mark_safe('<i class="fa fa-address-book" aria-hidden="true"></i>')),
    ('fa-address-book-o', mark_safe('<i class="fa fa-address-book-o" aria-hidden="true"></i>')),
    ('fa-address-card', mark_safe('<i class="fa fa-address-card" aria-hidden="true"></i>')),
    ('fa-address-card-o', mark_safe('<i class="fa fa-address-card-o" aria-hidden="true"></i>')),
    ('fa-bandcamp', mark_safe('<i class="fa fa-bandcamp" aria-hidden="true"></i>')),
    ('fa-certificate', mark_safe('<i class="fa fa-certificate" aria-hidden="true"></i>')),
    ('fa-check', mark_safe('<i class="fa fa-check" aria-hidden="true"></i>')),
    ('fa-check-circle', mark_safe('<i class="fa fa-check-circle" aria-hidden="true"></i>')),
    ('fa-check-circle-o', mark_safe('<i class="fa fa-check-circle-o" aria-hidden="true"></i>')),
    ('fa-check-square', mark_safe('<i class="fa fa-check-square" aria-hidden="true"></i>')),
    ('fa-check-square-o', mark_safe('<i class="fa fa-check-square-o" aria-hidden="true"></i>')),
    ('fa-child', mark_safe('<i class="fa fa-child" aria-hidden="true"></i>')),
    ('fa-circle', mark_safe('<i class="fa fa-circle" aria-hidden="true"></i>')),
    ('fa-circle-o', mark_safe('<i class="fa fa-circle-o" aria-hidden="true"></i>')),
    ('fa-circle-o-notch', mark_safe('<i class="fa fa-circle-o-notch" aria-hidden="true"></i>')),
    ('fa-circle-thin', mark_safe('<i class="fa fa-circle-thin" aria-hidden="true"></i>')),
    ('fa-clock-o', mark_safe('<i class="fa fa-clock-o" aria-hidden="true"></i>')),
    ('fa-clone', mark_safe('<i class="fa fa-clone" aria-hidden="true"></i>')),
    ('fa-close', mark_safe('<i class="fa fa-close" aria-hidden="true"></i>')),
    ('fa-cloud', mark_safe('<i class="fa fa-cloud" aria-hidden="true"></i>')),
    ('fa-cloud-download', mark_safe('<i class="fa fa-cloud-download" aria-hidden="true"></i>')),
    ('fa-cloud-upload', mark_safe('<i class="fa fa-cloud-upload" aria-hidden="true"></i>')),
    ('fa-code', mark_safe('<i class="fa fa-code" aria-hidden="true"></i>')),
    ('fa-server', mark_safe('<i class="fa fa-server" aria-hidden="true"></i>')),
    ('fa-code-fork', mark_safe('<i class="fa fa-code-fork" aria-hidden="true"></i>')),
    ('fa-coffee', mark_safe('<i class="fa fa-coffee" aria-hidden="true"></i>')),
    ('fa-comment', mark_safe('<i class="fa fa-comment" aria-hidden="true"></i>')),
    ('fa-comment-o', mark_safe('<i class="fa fa-comment-o" aria-hidden="true"></i>')),
    ('fa-commenting', mark_safe('<i class="fa fa-commenting" aria-hidden="true"></i>')),
    ('fa-commenting-o', mark_safe('<i class="fa fa-commenting-o" aria-hidden="true"></i>')),
    ('fa-comments', mark_safe('<i class="fa fa-comments" aria-hidden="true"></i>')),
    ('fa-comments-o', mark_safe('<i class="fa fa-comments-o" aria-hidden="true"></i>')),
    ('fa-compass', mark_safe('<i class="fa fa-compass" aria-hidden="true"></i>')),
    ('fa-copyright', mark_safe('<i class="fa fa-copyright" aria-hidden="true"></i>')),
    ('fa-creative-commons', mark_safe('<i class="fa fa-creative-commons" aria-hidden="true"></i>')),
    ('fa-credit-card', mark_safe('<i class="fa fa-credit-card" aria-hidden="true"></i>')),
    ('fa-credit-card-alt', mark_safe('<i class="fa fa-credit-card-alt" aria-hidden="true"></i>')),
    ('fa-crop', mark_safe('<i class="fa fa-crop" aria-hidden="true"></i>')),
    ('fa-crosshairs', mark_safe('<i class="fa fa-crosshairs" aria-hidden="true"></i>')),
    ('fa-cube', mark_safe('<i class="fa fa-cube" aria-hidden="true"></i>')),
    ('fa-cubes', mark_safe('<i class="fa fa-cubes" aria-hidden="true"></i>')),
    ('fa-cutlery', mark_safe('<i class="fa fa-cutlery" aria-hidden="true"></i>')),
    ('fa-dashboard', mark_safe('<i class="fa fa-dashboard" aria-hidden="true"></i>')),
    ('fa-database', mark_safe('<i class="fa fa-database" aria-hidden="true"></i>')),
    ('fa-deaf', mark_safe('<i class="fa fa-deaf" aria-hidden="true"></i>')),
    ('fa-deafness', mark_safe('<i class="fa fa-deafness" aria-hidden="true"></i>')),
    ('fa-desktop', mark_safe('<i class="fa fa-desktop" aria-hidden="true"></i>')),
    ('fa-bath', mark_safe('<i class="fa fa-bath" aria-hidden="true"></i>')),
    ('fa-bathtub', mark_safe('<i class="fa fa-bathtub" aria-hidden="true"></i>')),
    ('fa-drivers-license', mark_safe('<i class="fa fa-drivers-license" aria-hidden="true"></i>')),
    ('fa-drivers-license-o', mark_safe('<i class="fa fa-drivers-license-o" aria-hidden="true"></i>')),
    ('fa-eercast', mark_safe('<i class="fa fa-eercast" aria-hidden="true"></i>')),
    ('fa-envelope-open', mark_safe('<i class="fa fa-envelope-open" aria-hidden="true"></i>')),
    ('fa-envelope-open-o', mark_safe('<i class="fa fa-envelope-open-o" aria-hidden="true"></i>')),
    ('fa-etsy', mark_safe('<i class="fa fa-etsy" aria-hidden="true"></i>')),
    ('fa-free-code-camp', mark_safe('<i class="fa fa-free-code-camp" aria-hidden="true"></i>')),
    ('fa-grav', mark_safe('<i class="fa fa-grav" aria-hidden="true"></i>')),
    ('fa-handshake-o', mark_safe('<i class="fa fa-handshake-o" aria-hidden="true"></i>')),
    ('fa-id-badge', mark_safe('<i class="fa fa-id-badge" aria-hidden="true"></i>')),
    ('fa-id-card', mark_safe('<i class="fa fa-id-card" aria-hidden="true"></i>')),
    ('fa-id-card-o', mark_safe('<i class="fa fa-id-card-o" aria-hidden="true"></i>')),
    ('fa-imdb', mark_safe('<i class="fa fa-imdb" aria-hidden="true"></i>')),
    ('fa-linode', mark_safe('<i class="fa fa-linode" aria-hidden="true"></i>')),
    ('fa-meetup', mark_safe('<i class="fa fa-meetup" aria-hidden="true"></i>')),
    ('fa-microchip', mark_safe('<i class="fa fa-microchip" aria-hidden="true"></i>')),
    ('fa-podcast', mark_safe('<i class="fa fa-podcast" aria-hidden="true"></i>')),
    ('fa-quora', mark_safe('<i class="fa fa-quora" aria-hidden="true"></i>')),
    ('fa-ravelry', mark_safe('<i class="fa fa-ravelry" aria-hidden="true"></i>')),
    ('fa-s15', mark_safe('<i class="fa fa-s15" aria-hidden="true"></i>')),
    ('fa-shower', mark_safe('<i class="fa fa-shower" aria-hidden="true"></i>')),
    ('fa-snowflake-o', mark_safe('<i class="fa fa-snowflake-o" aria-hidden="true"></i>')),
    ('fa-superpowers', mark_safe('<i class="fa fa-superpowers" aria-hidden="true"></i>')),
    ('fa-telegram', mark_safe('<i class="fa fa-telegram" aria-hidden="true"></i>')),
    ('fa-thermometer', mark_safe('<i class="fa fa-thermometer" aria-hidden="true"></i>')),
    ('fa-thermometer-0', mark_safe('<i class="fa fa-thermometer-0" aria-hidden="true"></i>')),
    ('fa-thermometer-1', mark_safe('<i class="fa fa-thermometer-1" aria-hidden="true"></i>')),
    ('fa-thermometer-2', mark_safe('<i class="fa fa-thermometer-2" aria-hidden="true"></i>')),
    ('fa-thermometer-3', mark_safe('<i class="fa fa-thermometer-3" aria-hidden="true"></i>')),
    ('fa-thermometer-4', mark_safe('<i class="fa fa-thermometer-4" aria-hidden="true"></i>')),
    ('fa-thermometer-empty', mark_safe('<i class="fa fa-thermometer-empty" aria-hidden="true"></i>')),
    ('fa-thermometer-full', mark_safe('<i class="fa fa-thermometer-full" aria-hidden="true"></i>')),
    ('fa-thermometer-half', mark_safe('<i class="fa fa-thermometer-half" aria-hidden="true"></i>')),
    ('fa-thermometer-quarter', mark_safe('<i class="fa fa-thermometer-quarter" aria-hidden="true"></i>')),
    ('fa-thermometer-three-quarters', mark_safe('<i class="fa fa-thermometer-three-quarters" aria-hidden="true"></i>')),
    ('fa-times-rectangle', mark_safe('<i class="fa fa-times-rectangle" aria-hidden="true"></i>')),
    ('fa-times-rectangle-o', mark_safe('<i class="fa fa-times-rectangle-o" aria-hidden="true"></i>')),
    ('fa-user-circle', mark_safe('<i class="fa fa-user-circle" aria-hidden="true"></i>')),
    ('fa-user-circle-o', mark_safe('<i class="fa fa-user-circle-o" aria-hidden="true"></i>')),
    ('fa-user-o', mark_safe('<i class="fa fa-user-o" aria-hidden="true"></i>')),
    ('fa-vcard', mark_safe('<i class="fa fa-vcard" aria-hidden="true"></i>')),
    ('fa-vcard-o', mark_safe('<i class="fa fa-vcard-o" aria-hidden="true"></i>')),
    ('fa-window-close', mark_safe('<i class="fa fa-window-close" aria-hidden="true"></i>')),
    ('fa-window-close-o', mark_safe('<i class="fa fa-window-close-o" aria-hidden="true"></i>')),
    ('fa-window-maximize', mark_safe('<i class="fa fa-window-maximize" aria-hidden="true"></i>')),
    ('fa-window-minimize', mark_safe('<i class="fa fa-window-minimize" aria-hidden="true"></i>')),
    ('fa-window-restore', mark_safe('<i class="fa fa-window-restore" aria-hidden="true"></i>')),
    ('fa-wpexplorer', mark_safe('<i class="fa fa-wpexplorer" aria-hidden="true"></i>')),
    ('fa-address-book', mark_safe('<i class="fa fa-address-book" aria-hidden="true"></i>')),
    ('fa-address-book-o', mark_safe('<i class="fa fa-address-book-o" aria-hidden="true"></i>')),
    ('fa-address-card', mark_safe('<i class="fa fa-address-card" aria-hidden="true"></i>')),
    ('fa-address-card-o', mark_safe('<i class="fa fa-address-card-o" aria-hidden="true"></i>')),
    ('fa-adjust', mark_safe('<i class="fa fa-adjust" aria-hidden="true"></i>')),
    ('fa-american-sign-language-interpreting',
     mark_safe('<i class="fa fa-american-sign-language-interpreting" aria-hidden="true"></i>')),
    ('fa-anchor', mark_safe('<i class="fa fa-anchor" aria-hidden="true"></i>')),
    ('fa-archive', mark_safe('<i class="fa fa-archive" aria-hidden="true"></i>')),
    ('fa-area-chart', mark_safe('<i class="fa fa-area-chart" aria-hidden="true"></i>')),
    ('fa-arrows', mark_safe('<i class="fa fa-arrows" aria-hidden="true"></i>')),
    ('fa-arrows-h', mark_safe('<i class="fa fa-arrows-h" aria-hidden="true"></i>')),
    ('fa-arrows-v', mark_safe('<i class="fa fa-arrows-v" aria-hidden="true"></i>')),
    ('fa-asl-interpreting', mark_safe('<i class="fa fa-asl-interpreting" aria-hidden="true"></i>')),
    ('fa-assistive-listening-systems',
     mark_safe('<i class="fa fa-assistive-listening-systems" aria-hidden="true"></i>')),
    ('fa-asterisk', mark_safe('<i class="fa fa-asterisk" aria-hidden="true"></i>')),
    ('fa-at', mark_safe('<i class="fa fa-at" aria-hidden="true"></i>')),
    ('fa-audio-description', mark_safe('<i class="fa fa-audio-description" aria-hidden="true"></i>')),
    ('fa-automobile', mark_safe('<i class="fa fa-automobile" aria-hidden="true"></i>')),
    ('fa-balance-scale', mark_safe('<i class="fa fa-balance-scale" aria-hidden="true"></i>')),
    ('fa-ban', mark_safe('<i class="fa fa-ban" aria-hidden="true"></i>')),
    ('fa-bank', mark_safe('<i class="fa fa-bank" aria-hidden="true"></i>')),
    ('fa-bar-chart', mark_safe('<i class="fa fa-bar-chart" aria-hidden="true"></i>')),
    ('fa-bar-chart-o', mark_safe('<i class="fa fa-bar-chart-o" aria-hidden="true"></i>')),
    ('fa-barcode', mark_safe('<i class="fa fa-barcode" aria-hidden="true"></i>')),
    ('fa-bars', mark_safe('<i class="fa fa-bars" aria-hidden="true"></i>')),
    ('fa-bath', mark_safe('<i class="fa fa-bath" aria-hidden="true"></i>')),
    ('fa-bathtub', mark_safe('<i class="fa fa-bathtub" aria-hidden="true"></i>')),
    ('fa-battery', mark_safe('<i class="fa fa-battery" aria-hidden="true"></i>')),
    ('fa-battery-0', mark_safe('<i class="fa fa-battery-0" aria-hidden="true"></i>')),
    ('fa-battery-1', mark_safe('<i class="fa fa-battery-1" aria-hidden="true"></i>')),
    ('fa-battery-2', mark_safe('<i class="fa fa-battery-2" aria-hidden="true"></i>')),
    ('fa-battery-3', mark_safe('<i class="fa fa-battery-3" aria-hidden="true"></i>')),
    ('fa-battery-4', mark_safe('<i class="fa fa-battery-4" aria-hidden="true"></i>')),
    ('fa-battery-empty', mark_safe('<i class="fa fa-battery-empty" aria-hidden="true"></i>')),
    ('fa-battery-full', mark_safe('<i class="fa fa-battery-full" aria-hidden="true"></i>')),
    ('fa-battery-half', mark_safe('<i class="fa fa-battery-half" aria-hidden="true"></i>')),
    ('fa-battery-quarter', mark_safe('<i class="fa fa-battery-quarter" aria-hidden="true"></i>')),
    ('fa-battery-three-quarters', mark_safe('<i class="fa fa-battery-three-quarters" aria-hidden="true"></i>')),
    ('fa-bed', mark_safe('<i class="fa fa-bed" aria-hidden="true"></i>')),
    ('fa-beer', mark_safe('<i class="fa fa-beer" aria-hidden="true"></i>')),
    ('fa-bell', mark_safe('<i class="fa fa-bell" aria-hidden="true"></i>')),
    ('fa-bell-o', mark_safe('<i class="fa fa-bell-o" aria-hidden="true"></i>')),
    ('fa-bell-slash', mark_safe('<i class="fa fa-bell-slash" aria-hidden="true"></i>')),
    ('fa-bell-slash-o', mark_safe('<i class="fa fa-bell-slash-o" aria-hidden="true"></i>')),
    ('fa-bicycle', mark_safe('<i class="fa fa-bicycle" aria-hidden="true"></i>')),
    ('fa-binoculars', mark_safe('<i class="fa fa-binoculars" aria-hidden="true"></i>')),
    ('fa-birthday-cake', mark_safe('<i class="fa fa-birthday-cake" aria-hidden="true"></i>')),
    ('fa-blind', mark_safe('<i class="fa fa-blind" aria-hidden="true"></i>')),
    ('fa-bluetooth', mark_safe('<i class="fa fa-bluetooth" aria-hidden="true"></i>')),
    ('fa-bluetooth-b', mark_safe('<i class="fa fa-bluetooth-b" aria-hidden="true"></i>')),
    ('fa-bolt', mark_safe('<i class="fa fa-bolt" aria-hidden="true"></i>')),
    ('fa-bomb', mark_safe('<i class="fa fa-bomb" aria-hidden="true"></i>')),
    ('fa-book', mark_safe('<i class="fa fa-book" aria-hidden="true"></i>')),
    ('fa-bookmark', mark_safe('<i class="fa fa-bookmark" aria-hidden="true"></i>')),
    ('fa-bookmark-o', mark_safe('<i class="fa fa-bookmark-o" aria-hidden="true"></i>')),
    ('fa-braille', mark_safe('<i class="fa fa-braille" aria-hidden="true"></i>')),
    ('fa-briefcase', mark_safe('<i class="fa fa-briefcase" aria-hidden="true"></i>')),
    ('fa-bug', mark_safe('<i class="fa fa-bug" aria-hidden="true"></i>')),
    ('fa-building', mark_safe('<i class="fa fa-building" aria-hidden="true"></i>')),
    ('fa-building-o', mark_safe('<i class="fa fa-building-o" aria-hidden="true"></i>')),
    ('fa-bullhorn', mark_safe('<i class="fa fa-bullhorn" aria-hidden="true"></i>')),
    ('fa-bullseye', mark_safe('<i class="fa fa-bullseye" aria-hidden="true"></i>')),
    ('fa-bus', mark_safe('<i class="fa fa-bus" aria-hidden="true"></i>')),
    ('fa-cab', mark_safe('<i class="fa fa-cab" aria-hidden="true"></i>')),
    ('fa-calculator', mark_safe('<i class="fa fa-calculator" aria-hidden="true"></i>')),
    ('fa-calendar', mark_safe('<i class="fa fa-calendar" aria-hidden="true"></i>')),
    ('fa-calendar-check-o', mark_safe('<i class="fa fa-calendar-check-o" aria-hidden="true"></i>')),
    ('fa-calendar-minus-o', mark_safe('<i class="fa fa-calendar-minus-o" aria-hidden="true"></i>')),
    ('fa-calendar-o', mark_safe('<i class="fa fa-calendar-o" aria-hidden="true"></i>')),
    ('fa-calendar-plus-o', mark_safe('<i class="fa fa-calendar-plus-o" aria-hidden="true"></i>')),
    ('fa-calendar-times-o', mark_safe('<i class="fa fa-calendar-times-o" aria-hidden="true"></i>')),
    ('fa-camera', mark_safe('<i class="fa fa-camera" aria-hidden="true"></i>')),
    ('fa-camera-retro', mark_safe('<i class="fa fa-camera-retro" aria-hidden="true"></i>')),
    ('fa-car', mark_safe('<i class="fa fa-car" aria-hidden="true"></i>')),
    ('fa-caret-square-o-down', mark_safe('<i class="fa fa-caret-square-o-down" aria-hidden="true"></i>')),
    ('fa-caret-square-o-left', mark_safe('<i class="fa fa-caret-square-o-left" aria-hidden="true"></i>')),
    ('fa-caret-square-o-right', mark_safe('<i class="fa fa-caret-square-o-right" aria-hidden="true"></i>')),
    ('fa-caret-square-o-up', mark_safe('<i class="fa fa-caret-square-o-up" aria-hidden="true"></i>')),
    ('fa-cart-arrow-down', mark_safe('<i class="fa fa-cart-arrow-down" aria-hidden="true"></i>')),
    ('fa-cart-plus', mark_safe('<i class="fa fa-cart-plus" aria-hidden="true"></i>')),
    ('fa-cc', mark_safe('<i class="fa fa-cc" aria-hidden="true"></i>')),
    ('fa-diamond', mark_safe('<i class="fa fa-diamond" aria-hidden="true"></i>')),
    ('fa-dot-circle-o', mark_safe('<i class="fa fa-dot-circle-o" aria-hidden="true"></i>')),
    ('fa-download', mark_safe('<i class="fa fa-download" aria-hidden="true"></i>')),
    ('fa-drivers-license', mark_safe('<i class="fa fa-drivers-license" aria-hidden="true"></i>')),
    ('fa-drivers-license-o', mark_safe('<i class="fa fa-drivers-license-o" aria-hidden="true"></i>')),
    ('fa-edit', mark_safe('<i class="fa fa-edit" aria-hidden="true"></i>')),
    ('fa-ellipsis-h', mark_safe('<i class="fa fa-ellipsis-h" aria-hidden="true"></i>')),
    ('fa-ellipsis-v', mark_safe('<i class="fa fa-ellipsis-v" aria-hidden="true"></i>')),
    ('fa-envelope', mark_safe('<i class="fa fa-envelope" aria-hidden="true"></i>')),
    ('fa-envelope-o', mark_safe('<i class="fa fa-envelope-o" aria-hidden="true"></i>')),
    ('fa-envelope-open', mark_safe('<i class="fa fa-envelope-open" aria-hidden="true"></i>')),
    ('fa-envelope-open-o', mark_safe('<i class="fa fa-envelope-open-o" aria-hidden="true"></i>')),
    ('fa-envelope-square', mark_safe('<i class="fa fa-envelope-square" aria-hidden="true"></i>')),
    ('fa-eraser', mark_safe('<i class="fa fa-eraser" aria-hidden="true"></i>')),
    ('fa-exchange', mark_safe('<i class="fa fa-exchange" aria-hidden="true"></i>')),
    ('fa-exclamation', mark_safe('<i class="fa fa-exclamation" aria-hidden="true"></i>')),
    ('fa-exclamation-circle', mark_safe('<i class="fa fa-exclamation-circle" aria-hidden="true"></i>')),
    ('fa-exclamation-triangle', mark_safe('<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>')),
    ('fa-external-link', mark_safe('<i class="fa fa-external-link" aria-hidden="true"></i>')),
    ('fa-external-link-square', mark_safe('<i class="fa fa-external-link-square" aria-hidden="true"></i>')),
    ('fa-eye', mark_safe('<i class="fa fa-eye" aria-hidden="true"></i>')),
    ('fa-eye-slash', mark_safe('<i class="fa fa-eye-slash" aria-hidden="true"></i>')),
    ('fa-eyedropper', mark_safe('<i class="fa fa-eyedropper" aria-hidden="true"></i>')),
    ('fa-fax', mark_safe('<i class="fa fa-fax" aria-hidden="true"></i>')),
    ('fa-feed', mark_safe('<i class="fa fa-feed" aria-hidden="true"></i>')),
    ('fa-female', mark_safe('<i class="fa fa-female" aria-hidden="true"></i>')),
    ('fa-fighter-jet', mark_safe('<i class="fa fa-fighter-jet" aria-hidden="true"></i>')),
    ('fa-file-archive-o', mark_safe('<i class="fa fa-file-archive-o" aria-hidden="true"></i>')),
    ('fa-file-audio-o', mark_safe('<i class="fa fa-file-audio-o" aria-hidden="true"></i>')),
    ('fa-file-code-o', mark_safe('<i class="fa fa-file-code-o" aria-hidden="true"></i>')),
    ('fa-file-excel-o', mark_safe('<i class="fa fa-file-excel-o" aria-hidden="true"></i>')),
    ('fa-file-image-o', mark_safe('<i class="fa fa-file-image-o" aria-hidden="true"></i>')),
    ('fa-file-movie-o', mark_safe('<i class="fa fa-file-movie-o" aria-hidden="true"></i>')),
    ('fa-file-pdf-o', mark_safe('<i class="fa fa-file-pdf-o" aria-hidden="true"></i>')),
    ('fa-file-photo-o', mark_safe('<i class="fa fa-file-photo-o" aria-hidden="true"></i>')),
    ('fa-file-picture-o', mark_safe('<i class="fa fa-file-picture-o" aria-hidden="true"></i>')),
    ('fa-file-powerpoint-o', mark_safe('<i class="fa fa-file-powerpoint-o" aria-hidden="true"></i>')),
    ('fa-file-sound-o', mark_safe('<i class="fa fa-file-sound-o" aria-hidden="true"></i>')),
    ('fa-file-video-o', mark_safe('<i class="fa fa-file-video-o" aria-hidden="true"></i>')),
    ('fa-file-word-o', mark_safe('<i class="fa fa-file-word-o" aria-hidden="true"></i>')),
    ('fa-file-zip-o', mark_safe('<i class="fa fa-file-zip-o" aria-hidden="true"></i>')),
    ('fa-film', mark_safe('<i class="fa fa-film" aria-hidden="true"></i>')),
    ('fa-filter', mark_safe('<i class="fa fa-filter" aria-hidden="true"></i>')),
    ('fa-fire', mark_safe('<i class="fa fa-fire" aria-hidden="true"></i>')),
    ('fa-fire-extinguisher', mark_safe('<i class="fa fa-fire-extinguisher" aria-hidden="true"></i>')),
    ('fa-flag', mark_safe('<i class="fa fa-flag" aria-hidden="true"></i>')),
    ('fa-flag-checkered', mark_safe('<i class="fa fa-flag-checkered" aria-hidden="true"></i>')),
    ('fa-flag-o', mark_safe('<i class="fa fa-flag-o" aria-hidden="true"></i>')),
    ('fa-flash', mark_safe('<i class="fa fa-flash" aria-hidden="true"></i>')),
    ('fa-flask', mark_safe('<i class="fa fa-flask" aria-hidden="true"></i>')),
    ('fa-folder', mark_safe('<i class="fa fa-folder" aria-hidden="true"></i>')),
    ('fa-folder-o', mark_safe('<i class="fa fa-folder-o" aria-hidden="true"></i>')),
    ('fa-folder-open', mark_safe('<i class="fa fa-folder-open" aria-hidden="true"></i>')),
    ('fa-folder-open-o', mark_safe('<i class="fa fa-folder-open-o" aria-hidden="true"></i>')),
    ('fa-frown-o', mark_safe('<i class="fa fa-frown-o" aria-hidden="true"></i>')),
    ('fa-futbol-o', mark_safe('<i class="fa fa-futbol-o" aria-hidden="true"></i>')),
    ('fa-gamepad', mark_safe('<i class="fa fa-gamepad" aria-hidden="true"></i>')),
    ('fa-gavel', mark_safe('<i class="fa fa-gavel" aria-hidden="true"></i>')),
    ('fa-gear', mark_safe('<i class="fa fa-gear" aria-hidden="true"></i>')),
    ('fa-gears', mark_safe('<i class="fa fa-gears" aria-hidden="true"></i>')),
    ('fa-gift', mark_safe('<i class="fa fa-gift" aria-hidden="true"></i>')),
    ('fa-glass', mark_safe('<i class="fa fa-glass" aria-hidden="true"></i>')),
    ('fa-globe', mark_safe('<i class="fa fa-globe" aria-hidden="true"></i>')),
    ('fa-graduation-cap', mark_safe('<i class="fa fa-graduation-cap" aria-hidden="true"></i>')),
    ('fa-group', mark_safe('<i class="fa fa-group" aria-hidden="true"></i>')),
    ('fa-hand-grab-o', mark_safe('<i class="fa fa-hand-grab-o" aria-hidden="true"></i>')),
    ('fa-hand-lizard-o', mark_safe('<i class="fa fa-hand-lizard-o" aria-hidden="true"></i>')),
    ('fa-hand-paper-o', mark_safe('<i class="fa fa-hand-paper-o" aria-hidden="true"></i>')),
    ('fa-hand-peace-o', mark_safe('<i class="fa fa-hand-peace-o" aria-hidden="true"></i>')),
    ('fa-hand-pointer-o', mark_safe('<i class="fa fa-hand-pointer-o" aria-hidden="true"></i>')),
    ('fa-hand-rock-o', mark_safe('<i class="fa fa-hand-rock-o" aria-hidden="true"></i>')),
    ('fa-hand-scissors-o', mark_safe('<i class="fa fa-hand-scissors-o" aria-hidden="true"></i>')),
    ('fa-hand-spock-o', mark_safe('<i class="fa fa-hand-spock-o" aria-hidden="true"></i>')),
    ('fa-hand-stop-o', mark_safe('<i class="fa fa-hand-stop-o" aria-hidden="true"></i>')),
    ('fa-handshake-o', mark_safe('<i class="fa fa-handshake-o" aria-hidden="true"></i>')),
    ('fa-hard-of-hearing', mark_safe('<i class="fa fa-hard-of-hearing" aria-hidden="true"></i>')),
    ('fa-hashtag', mark_safe('<i class="fa fa-hashtag" aria-hidden="true"></i>')),
    ('fa-hdd-o', mark_safe('<i class="fa fa-hdd-o" aria-hidden="true"></i>')),
    ('fa-headphones', mark_safe('<i class="fa fa-headphones" aria-hidden="true"></i>')),
    ('fa-heart', mark_safe('<i class="fa fa-heart" aria-hidden="true"></i>')),
    ('fa-heart-o', mark_safe('<i class="fa fa-heart-o" aria-hidden="true"></i>')),
    ('fa-heartbeat', mark_safe('<i class="fa fa-heartbeat" aria-hidden="true"></i>')),
    ('fa-history', mark_safe('<i class="fa fa-history" aria-hidden="true"></i>')),
    ('fa-home', mark_safe('<i class="fa fa-home" aria-hidden="true"></i>')),
    ('fa-hotel', mark_safe('<i class="fa fa-hotel" aria-hidden="true"></i>')),
    ('fa-hourglass', mark_safe('<i class="fa fa-hourglass" aria-hidden="true"></i>')),
    ('fa-hourglass-1', mark_safe('<i class="fa fa-hourglass-1" aria-hidden="true"></i>')),
    ('fa-hourglass-2', mark_safe('<i class="fa fa-hourglass-2" aria-hidden="true"></i>')),
    ('fa-hourglass-3', mark_safe('<i class="fa fa-hourglass-3" aria-hidden="true"></i>')),
    ('fa-hourglass-end', mark_safe('<i class="fa fa-hourglass-end" aria-hidden="true"></i>')),
    ('fa-hourglass-half', mark_safe('<i class="fa fa-hourglass-half" aria-hidden="true"></i>')),
    ('fa-hourglass-o', mark_safe('<i class="fa fa-hourglass-o" aria-hidden="true"></i>')),
    ('fa-hourglass-start', mark_safe('<i class="fa fa-hourglass-start" aria-hidden="true"></i>')),
    ('fa-i-cursor', mark_safe('<i class="fa fa-i-cursor" aria-hidden="true"></i>')),
    ('fa-id-badge', mark_safe('<i class="fa fa-id-badge" aria-hidden="true"></i>')),
    ('fa-id-card', mark_safe('<i class="fa fa-id-card" aria-hidden="true"></i>')),
    ('fa-id-card-o', mark_safe('<i class="fa fa-id-card-o" aria-hidden="true"></i>')),
    ('fa-image', mark_safe('<i class="fa fa-image" aria-hidden="true"></i>')),
    ('fa-inbox', mark_safe('<i class="fa fa-inbox" aria-hidden="true"></i>')),
    ('fa-industry', mark_safe('<i class="fa fa-industry" aria-hidden="true"></i>')),
    ('fa-info', mark_safe('<i class="fa fa-info" aria-hidden="true"></i>')),
    ('fa-info-circle', mark_safe('<i class="fa fa-info-circle" aria-hidden="true"></i>')),
    ('fa-institution', mark_safe('<i class="fa fa-institution" aria-hidden="true"></i>')),
    ('fa-key', mark_safe('<i class="fa fa-key" aria-hidden="true"></i>')),
    ('fa-keyboard-o', mark_safe('<i class="fa fa-keyboard-o" aria-hidden="true"></i>')),
    ('fa-language', mark_safe('<i class="fa fa-language" aria-hidden="true"></i>')),
    ('fa-laptop', mark_safe('<i class="fa fa-laptop" aria-hidden="true"></i>')),
    ('fa-leaf', mark_safe('<i class="fa fa-leaf" aria-hidden="true"></i>')),
    ('fa-legal', mark_safe('<i class="fa fa-legal" aria-hidden="true"></i>')),
    ('fa-lemon-o', mark_safe('<i class="fa fa-lemon-o" aria-hidden="true"></i>')),
    ('fa-level-down', mark_safe('<i class="fa fa-level-down" aria-hidden="true"></i>')),
    ('fa-level-up', mark_safe('<i class="fa fa-level-up" aria-hidden="true"></i>')),
    ('fa-life-bouy', mark_safe('<i class="fa fa-life-bouy" aria-hidden="true"></i>')),
    ('fa-life-buoy', mark_safe('<i class="fa fa-life-buoy" aria-hidden="true"></i>')),
    ('fa-life-ring', mark_safe('<i class="fa fa-life-ring" aria-hidden="true"></i>')),
    ('fa-life-saver', mark_safe('<i class="fa fa-life-saver" aria-hidden="true"></i>')),
    ('fa-lightbulb-o', mark_safe('<i class="fa fa-lightbulb-o" aria-hidden="true"></i>')),
    ('fa-line-chart', mark_safe('<i class="fa fa-line-chart" aria-hidden="true"></i>')),
    ('fa-location-arrow', mark_safe('<i class="fa fa-location-arrow" aria-hidden="true"></i>')),
    ('fa-lock', mark_safe('<i class="fa fa-lock" aria-hidden="true"></i>')),
    ('fa-low-vision', mark_safe('<i class="fa fa-low-vision" aria-hidden="true"></i>')),
    ('fa-magic', mark_safe('<i class="fa fa-magic" aria-hidden="true"></i>')),
    ('fa-magnet', mark_safe('<i class="fa fa-magnet" aria-hidden="true"></i>')),
    ('fa-mail-forward', mark_safe('<i class="fa fa-mail-forward" aria-hidden="true"></i>')),
    ('fa-mail-reply', mark_safe('<i class="fa fa-mail-reply" aria-hidden="true"></i>')),
    ('fa-mail-reply-all', mark_safe('<i class="fa fa-mail-reply-all" aria-hidden="true"></i>')),
    ('fa-male', mark_safe('<i class="fa fa-male" aria-hidden="true"></i>')),
    ('fa-map', mark_safe('<i class="fa fa-map" aria-hidden="true"></i>')),
    ('fa-map-marker', mark_safe('<i class="fa fa-map-marker" aria-hidden="true"></i>')),
    ('fa-map-o', mark_safe('<i class="fa fa-map-o" aria-hidden="true"></i>')),
    ('fa-map-pin', mark_safe('<i class="fa fa-map-pin" aria-hidden="true"></i>')),
    ('fa-map-signs', mark_safe('<i class="fa fa-map-signs" aria-hidden="true"></i>')),
    ('fa-meh-o', mark_safe('<i class="fa fa-meh-o" aria-hidden="true"></i>')),
    ('fa-microchip', mark_safe('<i class="fa fa-microchip" aria-hidden="true"></i>')),
    ('fa-microphone', mark_safe('<i class="fa fa-microphone" aria-hidden="true"></i>')),
    ('fa-microphone-slash', mark_safe('<i class="fa fa-microphone-slash" aria-hidden="true"></i>')),
    ('fa-minus', mark_safe('<i class="fa fa-minus" aria-hidden="true"></i>')),
    ('fa-minus-circle', mark_safe('<i class="fa fa-minus-circle" aria-hidden="true"></i>')),
    ('fa-minus-square', mark_safe('<i class="fa fa-minus-square" aria-hidden="true"></i>')),
    ('fa-minus-square-o', mark_safe('<i class="fa fa-minus-square-o" aria-hidden="true"></i>')),
    ('fa-mobile', mark_safe('<i class="fa fa-mobile" aria-hidden="true"></i>')),
    ('fa-mobile-phone', mark_safe('<i class="fa fa-mobile-phone" aria-hidden="true"></i>')),
    ('fa-money', mark_safe('<i class="fa fa-money" aria-hidden="true"></i>')),
    ('fa-moon-o', mark_safe('<i class="fa fa-moon-o" aria-hidden="true"></i>')),
    ('fa-mortar-board', mark_safe('<i class="fa fa-mortar-board" aria-hidden="true"></i>')),
    ('fa-motorcycle', mark_safe('<i class="fa fa-motorcycle" aria-hidden="true"></i>')),
    ('fa-mouse-pointer', mark_safe('<i class="fa fa-mouse-pointer" aria-hidden="true"></i>')),
    ('fa-music', mark_safe('<i class="fa fa-music" aria-hidden="true"></i>')),
    ('fa-navicon', mark_safe('<i class="fa fa-navicon" aria-hidden="true"></i>')),
    ('fa-newspaper-o', mark_safe('<i class="fa fa-newspaper-o" aria-hidden="true"></i>')),
    ('fa-object-group', mark_safe('<i class="fa fa-object-group" aria-hidden="true"></i>')),
    ('fa-object-ungroup', mark_safe('<i class="fa fa-object-ungroup" aria-hidden="true"></i>')),
    ('fa-paint-brush', mark_safe('<i class="fa fa-paint-brush" aria-hidden="true"></i>')),
    ('fa-paper-plane', mark_safe('<i class="fa fa-paper-plane" aria-hidden="true"></i>')),
    ('fa-paper-plane-o', mark_safe('<i class="fa fa-paper-plane-o" aria-hidden="true"></i>')),
    ('fa-paw', mark_safe('<i class="fa fa-paw" aria-hidden="true"></i>')),
    ('fa-pencil', mark_safe('<i class="fa fa-pencil" aria-hidden="true"></i>')),
    ('fa-pencil-square', mark_safe('<i class="fa fa-pencil-square" aria-hidden="true"></i>')),
    ('fa-pencil-square-o', mark_safe('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>')),
    ('fa-percent', mark_safe('<i class="fa fa-percent" aria-hidden="true"></i>')),
    ('fa-phone', mark_safe('<i class="fa fa-phone" aria-hidden="true"></i>')),
    ('fa-phone-square', mark_safe('<i class="fa fa-phone-square" aria-hidden="true"></i>')),
    ('fa-photo', mark_safe('<i class="fa fa-photo" aria-hidden="true"></i>')),
    ('fa-picture-o', mark_safe('<i class="fa fa-picture-o" aria-hidden="true"></i>')),
    ('fa-pie-chart', mark_safe('<i class="fa fa-pie-chart" aria-hidden="true"></i>')),
    ('fa-plane', mark_safe('<i class="fa fa-plane" aria-hidden="true"></i>')),
    ('fa-plug', mark_safe('<i class="fa fa-plug" aria-hidden="true"></i>')),
    ('fa-plus', mark_safe('<i class="fa fa-plus" aria-hidden="true"></i>')),
    ('fa-plus-circle', mark_safe('<i class="fa fa-plus-circle" aria-hidden="true"></i>')),
    ('fa-plus-square', mark_safe('<i class="fa fa-plus-square" aria-hidden="true"></i>')),
    ('fa-plus-square-o', mark_safe('<i class="fa fa-plus-square-o" aria-hidden="true"></i>')),
    ('fa-podcast', mark_safe('<i class="fa fa-podcast" aria-hidden="true"></i>')),
    ('fa-power-off', mark_safe('<i class="fa fa-power-off" aria-hidden="true"></i>')),
    ('fa-print', mark_safe('<i class="fa fa-print" aria-hidden="true"></i>')),
    ('fa-puzzle-piece', mark_safe('<i class="fa fa-puzzle-piece" aria-hidden="true"></i>')),
    ('fa-qrcode', mark_safe('<i class="fa fa-qrcode" aria-hidden="true"></i>')),
    ('fa-question', mark_safe('<i class="fa fa-question" aria-hidden="true"></i>')),
    ('fa-question-circle', mark_safe('<i class="fa fa-question-circle" aria-hidden="true"></i>')),
    ('fa-question-circle-o', mark_safe('<i class="fa fa-question-circle-o" aria-hidden="true"></i>')),
    ('fa-quote-left', mark_safe('<i class="fa fa-quote-left" aria-hidden="true"></i>')),
    ('fa-quote-right', mark_safe('<i class="fa fa-quote-right" aria-hidden="true"></i>')),
    ('fa-random', mark_safe('<i class="fa fa-random" aria-hidden="true"></i>')),
    ('fa-recycle', mark_safe('<i class="fa fa-recycle" aria-hidden="true"></i>')),
    ('fa-refresh', mark_safe('<i class="fa fa-refresh" aria-hidden="true"></i>')),
    ('fa-registered', mark_safe('<i class="fa fa-registered" aria-hidden="true"></i>')),
    ('fa-remove', mark_safe('<i class="fa fa-remove" aria-hidden="true"></i>')),
    ('fa-reorder', mark_safe('<i class="fa fa-reorder" aria-hidden="true"></i>')),
    ('fa-reply', mark_safe('<i class="fa fa-reply" aria-hidden="true"></i>')),
    ('fa-reply-all', mark_safe('<i class="fa fa-reply-all" aria-hidden="true"></i>')),
    ('fa-retweet', mark_safe('<i class="fa fa-retweet" aria-hidden="true"></i>')),
    ('fa-road', mark_safe('<i class="fa fa-road" aria-hidden="true"></i>')),
    ('fa-rocket', mark_safe('<i class="fa fa-rocket" aria-hidden="true"></i>')),
    ('fa-rss', mark_safe('<i class="fa fa-rss" aria-hidden="true"></i>')),
    ('fa-rss-square', mark_safe('<i class="fa fa-rss-square" aria-hidden="true"></i>')),
    ('fa-s15', mark_safe('<i class="fa fa-s15" aria-hidden="true"></i>')),
    ('fa-search', mark_safe('<i class="fa fa-search" aria-hidden="true"></i>')),
    ('fa-search-minus', mark_safe('<i class="fa fa-search-minus" aria-hidden="true"></i>')),
    ('fa-search-plus', mark_safe('<i class="fa fa-search-plus" aria-hidden="true"></i>')),
    ('fa-send', mark_safe('<i class="fa fa-send" aria-hidden="true"></i>')),
    ('fa-send-o', mark_safe('<i class="fa fa-send-o" aria-hidden="true"></i>')),
    ('fa-share', mark_safe('<i class="fa fa-share" aria-hidden="true"></i>')),
    ('fa-share-alt', mark_safe('<i class="fa fa-share-alt" aria-hidden="true"></i>')),
    ('fa-share-alt-square', mark_safe('<i class="fa fa-share-alt-square" aria-hidden="true"></i>')),
    ('fa-share-square', mark_safe('<i class="fa fa-share-square" aria-hidden="true"></i>')),
    ('fa-share-square-o', mark_safe('<i class="fa fa-share-square-o" aria-hidden="true"></i>')),
    ('fa-shield', mark_safe('<i class="fa fa-shield" aria-hidden="true"></i>')),
    ('fa-ship', mark_safe('<i class="fa fa-ship" aria-hidden="true"></i>')),
    ('fa-shopping-bag', mark_safe('<i class="fa fa-shopping-bag" aria-hidden="true"></i>')),
    ('fa-shopping-basket', mark_safe('<i class="fa fa-shopping-basket" aria-hidden="true"></i>')),
    ('fa-shopping-cart', mark_safe('<i class="fa fa-shopping-cart" aria-hidden="true"></i>')),
    ('fa-shower', mark_safe('<i class="fa fa-shower" aria-hidden="true"></i>')),
    ('fa-sign-in', mark_safe('<i class="fa fa-sign-in" aria-hidden="true"></i>')),
    ('fa-sign-language', mark_safe('<i class="fa fa-sign-language" aria-hidden="true"></i>')),
    ('fa-sign-out', mark_safe('<i class="fa fa-sign-out" aria-hidden="true"></i>')),
    ('fa-signal', mark_safe('<i class="fa fa-signal" aria-hidden="true"></i>')),
    ('fa-signing', mark_safe('<i class="fa fa-signing" aria-hidden="true"></i>')),
    ('fa-sitemap', mark_safe('<i class="fa fa-sitemap" aria-hidden="true"></i>')),
    ('fa-sliders', mark_safe('<i class="fa fa-sliders" aria-hidden="true"></i>')),
    ('fa-smile-o', mark_safe('<i class="fa fa-smile-o" aria-hidden="true"></i>')),
    ('fa-snowflake-o', mark_safe('<i class="fa fa-snowflake-o" aria-hidden="true"></i>')),
    ('fa-soccer-ball-o', mark_safe('<i class="fa fa-soccer-ball-o" aria-hidden="true"></i>')),
    ('fa-sort', mark_safe('<i class="fa fa-sort" aria-hidden="true"></i>')),
    ('fa-sort-alpha-asc', mark_safe('<i class="fa fa-sort-alpha-asc" aria-hidden="true"></i>')),
    ('fa-sort-alpha-desc', mark_safe('<i class="fa fa-sort-alpha-desc" aria-hidden="true"></i>')),
    ('fa-sort-amount-asc', mark_safe('<i class="fa fa-sort-amount-asc" aria-hidden="true"></i>')),
    ('fa-sort-amount-desc', mark_safe('<i class="fa fa-sort-amount-desc" aria-hidden="true"></i>')),
    ('fa-sort-asc', mark_safe('<i class="fa fa-sort-asc" aria-hidden="true"></i>')),
    ('fa-sort-desc', mark_safe('<i class="fa fa-sort-desc" aria-hidden="true"></i>')),
    ('fa-sort-down', mark_safe('<i class="fa fa-sort-down" aria-hidden="true"></i>')),
    ('fa-sort-numeric-asc', mark_safe('<i class="fa fa-sort-numeric-asc" aria-hidden="true"></i>')),
    ('fa-sort-numeric-desc', mark_safe('<i class="fa fa-sort-numeric-desc" aria-hidden="true"></i>')),
    ('fa-sort-up', mark_safe('<i class="fa fa-sort-up" aria-hidden="true"></i>')),
    ('fa-space-shuttle', mark_safe('<i class="fa fa-space-shuttle" aria-hidden="true"></i>')),
    ('fa-spinner', mark_safe('<i class="fa fa-spinner" aria-hidden="true"></i>')),
    ('fa-spoon', mark_safe('<i class="fa fa-spoon" aria-hidden="true"></i>')),
    ('fa-square', mark_safe('<i class="fa fa-square" aria-hidden="true"></i>')),
    ('fa-square-o', mark_safe('<i class="fa fa-square-o" aria-hidden="true"></i>')),
    ('fa-star', mark_safe('<i class="fa fa-star" aria-hidden="true"></i>')),
    ('fa-star-half', mark_safe('<i class="fa fa-star-half" aria-hidden="true"></i>')),
    ('fa-star-half-empty', mark_safe('<i class="fa fa-star-half-empty" aria-hidden="true"></i>')),
    ('fa-star-half-full', mark_safe('<i class="fa fa-star-half-full" aria-hidden="true"></i>')),
    ('fa-star-half-o', mark_safe('<i class="fa fa-star-half-o" aria-hidden="true"></i>')),
    ('fa-star-o', mark_safe('<i class="fa fa-star-o" aria-hidden="true"></i>')),
    ('fa-sticky-note', mark_safe('<i class="fa fa-sticky-note" aria-hidden="true"></i>')),
    ('fa-sticky-note-o', mark_safe('<i class="fa fa-sticky-note-o" aria-hidden="true"></i>')),
    ('fa-street-view', mark_safe('<i class="fa fa-street-view" aria-hidden="true"></i>')),
    ('fa-suitcase', mark_safe('<i class="fa fa-suitcase" aria-hidden="true"></i>')),
    ('fa-sun-o', mark_safe('<i class="fa fa-sun-o" aria-hidden="true"></i>')),
    ('fa-support', mark_safe('<i class="fa fa-support" aria-hidden="true"></i>')),
    ('fa-tablet', mark_safe('<i class="fa fa-tablet" aria-hidden="true"></i>')),
    ('fa-tachometer', mark_safe('<i class="fa fa-tachometer" aria-hidden="true"></i>')),
    ('fa-tag', mark_safe('<i class="fa fa-tag" aria-hidden="true"></i>')),
    ('fa-tags', mark_safe('<i class="fa fa-tags" aria-hidden="true"></i>')),
    ('fa-tasks', mark_safe('<i class="fa fa-tasks" aria-hidden="true"></i>')),
    ('fa-taxi', mark_safe('<i class="fa fa-taxi" aria-hidden="true"></i>')),
    ('fa-television', mark_safe('<i class="fa fa-television" aria-hidden="true"></i>')),
    ('fa-terminal', mark_safe('<i class="fa fa-terminal" aria-hidden="true"></i>')),
    ('fa-thermometer', mark_safe('<i class="fa fa-thermometer" aria-hidden="true"></i>')),
    ('fa-thermometer-0', mark_safe('<i class="fa fa-thermometer-0" aria-hidden="true"></i>')),
    ('fa-thermometer-1', mark_safe('<i class="fa fa-thermometer-1" aria-hidden="true"></i>')),
    ('fa-thermometer-2', mark_safe('<i class="fa fa-thermometer-2" aria-hidden="true"></i>')),
    ('fa-thermometer-3', mark_safe('<i class="fa fa-thermometer-3" aria-hidden="true"></i>')),
    ('fa-thermometer-4', mark_safe('<i class="fa fa-thermometer-4" aria-hidden="true"></i>')),
    ('fa-thermometer-empty', mark_safe('<i class="fa fa-thermometer-empty" aria-hidden="true"></i>')),
    ('fa-thermometer-full', mark_safe('<i class="fa fa-thermometer-full" aria-hidden="true"></i>')),
    ('fa-thermometer-half', mark_safe('<i class="fa fa-thermometer-half" aria-hidden="true"></i>')),
    ('fa-thermometer-quarter', mark_safe('<i class="fa fa-thermometer-quarter" aria-hidden="true"></i>')),
    ('fa-thermometer-three-quarters', mark_safe('<i class="fa fa-thermometer-three-quarters" aria-hidden="true"></i>')),
    ('fa-thumb-tack', mark_safe('<i class="fa fa-thumb-tack" aria-hidden="true"></i>')),
    ('fa-thumbs-down', mark_safe('<i class="fa fa-thumbs-down" aria-hidden="true"></i>')),
    ('fa-thumbs-o-down', mark_safe('<i class="fa fa-thumbs-o-down" aria-hidden="true"></i>')),
    ('fa-thumbs-o-up', mark_safe('<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>')),
    ('fa-thumbs-up', mark_safe('<i class="fa fa-thumbs-up" aria-hidden="true"></i>')),
    ('fa-ticket', mark_safe('<i class="fa fa-ticket" aria-hidden="true"></i>')),
    ('fa-times', mark_safe('<i class="fa fa-times" aria-hidden="true"></i>')),
    ('fa-times-circle', mark_safe('<i class="fa fa-times-circle" aria-hidden="true"></i>')),
    ('fa-times-circle-o', mark_safe('<i class="fa fa-times-circle-o" aria-hidden="true"></i>')),
    ('fa-times-rectangle', mark_safe('<i class="fa fa-times-rectangle" aria-hidden="true"></i>')),
    ('fa-times-rectangle-o', mark_safe('<i class="fa fa-times-rectangle-o" aria-hidden="true"></i>')),
    ('fa-tint', mark_safe('<i class="fa fa-tint" aria-hidden="true"></i>')),
    ('fa-toggle-down', mark_safe('<i class="fa fa-toggle-down" aria-hidden="true"></i>')),
    ('fa-toggle-left', mark_safe('<i class="fa fa-toggle-left" aria-hidden="true"></i>')),
    ('fa-toggle-off', mark_safe('<i class="fa fa-toggle-off" aria-hidden="true"></i>')),
    ('fa-toggle-on', mark_safe('<i class="fa fa-toggle-on" aria-hidden="true"></i>')),
    ('fa-toggle-right', mark_safe('<i class="fa fa-toggle-right" aria-hidden="true"></i>')),
    ('fa-toggle-up', mark_safe('<i class="fa fa-toggle-up" aria-hidden="true"></i>')),
    ('fa-trademark', mark_safe('<i class="fa fa-trademark" aria-hidden="true"></i>')),
    ('fa-trash', mark_safe('<i class="fa fa-trash" aria-hidden="true"></i>')),
    ('fa-trash-o', mark_safe('<i class="fa fa-trash-o" aria-hidden="true"></i>')),
    ('fa-tree', mark_safe('<i class="fa fa-tree" aria-hidden="true"></i>')),
    ('fa-trophy', mark_safe('<i class="fa fa-trophy" aria-hidden="true"></i>')),
    ('fa-truck', mark_safe('<i class="fa fa-truck" aria-hidden="true"></i>')),
    ('fa-tty', mark_safe('<i class="fa fa-tty" aria-hidden="true"></i>')),
    ('fa-tv', mark_safe('<i class="fa fa-tv" aria-hidden="true"></i>')),
    ('fa-umbrella', mark_safe('<i class="fa fa-umbrella" aria-hidden="true"></i>')),
    ('fa-universal-access', mark_safe('<i class="fa fa-universal-access" aria-hidden="true"></i>')),
    ('fa-university', mark_safe('<i class="fa fa-university" aria-hidden="true"></i>')),
    ('fa-unlock', mark_safe('<i class="fa fa-unlock" aria-hidden="true"></i>')),
    ('fa-unlock-alt', mark_safe('<i class="fa fa-unlock-alt" aria-hidden="true"></i>')),
    ('fa-unsorted', mark_safe('<i class="fa fa-unsorted" aria-hidden="true"></i>')),
    ('fa-upload', mark_safe('<i class="fa fa-upload" aria-hidden="true"></i>')),
    ('fa-user', mark_safe('<i class="fa fa-user" aria-hidden="true"></i>')),
    ('fa-user-circle', mark_safe('<i class="fa fa-user-circle" aria-hidden="true"></i>')),
    ('fa-user-circle-o', mark_safe('<i class="fa fa-user-circle-o" aria-hidden="true"></i>')),
    ('fa-user-o', mark_safe('<i class="fa fa-user-o" aria-hidden="true"></i>')),
    ('fa-user-plus', mark_safe('<i class="fa fa-user-plus" aria-hidden="true"></i>')),
    ('fa-user-secret', mark_safe('<i class="fa fa-user-secret" aria-hidden="true"></i>')),
    ('fa-user-times', mark_safe('<i class="fa fa-user-times" aria-hidden="true"></i>')),
    ('fa-users', mark_safe('<i class="fa fa-users" aria-hidden="true"></i>')),
    ('fa-vcard', mark_safe('<i class="fa fa-vcard" aria-hidden="true"></i>')),
    ('fa-vcard-o', mark_safe('<i class="fa fa-vcard-o" aria-hidden="true"></i>')),
    ('fa-video-camera', mark_safe('<i class="fa fa-video-camera" aria-hidden="true"></i>')),
    ('fa-volume-control-phone', mark_safe('<i class="fa fa-volume-control-phone" aria-hidden="true"></i>')),
    ('fa-volume-down', mark_safe('<i class="fa fa-volume-down" aria-hidden="true"></i>')),
    ('fa-volume-off', mark_safe('<i class="fa fa-volume-off" aria-hidden="true"></i>')),
    ('fa-volume-up', mark_safe('<i class="fa fa-volume-up" aria-hidden="true"></i>')),
    ('fa-warning', mark_safe('<i class="fa fa-warning" aria-hidden="true"></i>')),
    ('fa-wheelchair', mark_safe('<i class="fa fa-wheelchair" aria-hidden="true"></i>')),
    ('fa-wheelchair-alt', mark_safe('<i class="fa fa-wheelchair-alt" aria-hidden="true"></i>')),
    ('fa-wifi', mark_safe('<i class="fa fa-wifi" aria-hidden="true"></i>')),
    ('fa-window-close', mark_safe('<i class="fa fa-window-close" aria-hidden="true"></i>')),
    ('fa-window-close-o', mark_safe('<i class="fa fa-window-close-o" aria-hidden="true"></i>')),
    ('fa-window-maximize', mark_safe('<i class="fa fa-window-maximize" aria-hidden="true"></i>')),
    ('fa-window-minimize', mark_safe('<i class="fa fa-window-minimize" aria-hidden="true"></i>')),
    ('fa-window-restore', mark_safe('<i class="fa fa-window-restore" aria-hidden="true"></i>')),
    ('fa-wrench', mark_safe('<i class="fa fa-wrench" aria-hidden="true"></i>')),
    ('fa-american-sign-language-interpreting',
     mark_safe('<i class="fa fa-american-sign-language-interpreting" aria-hidden="true"></i>')),
    ('fa-asl-interpreting', mark_safe('<i class="fa fa-asl-interpreting" aria-hidden="true"></i>')),
    ('fa-assistive-listening-systems',
     mark_safe('<i class="fa fa-assistive-listening-systems" aria-hidden="true"></i>')),
    ('fa-audio-description', mark_safe('<i class="fa fa-audio-description" aria-hidden="true"></i>')),
    ('fa-blind', mark_safe('<i class="fa fa-blind" aria-hidden="true"></i>')),
    ('fa-braille', mark_safe('<i class="fa fa-braille" aria-hidden="true"></i>')),
    ('fa-cc', mark_safe('<i class="fa fa-cc" aria-hidden="true"></i>')),
    ('fa-deaf', mark_safe('<i class="fa fa-deaf" aria-hidden="true"></i>')),
    ('fa-deafness', mark_safe('<i class="fa fa-deafness" aria-hidden="true"></i>')),
    ('fa-hard-of-hearing', mark_safe('<i class="fa fa-hard-of-hearing" aria-hidden="true"></i>')),
    ('fa-low-vision', mark_safe('<i class="fa fa-low-vision" aria-hidden="true"></i>')),
    ('fa-question-circle-o', mark_safe('<i class="fa fa-question-circle-o" aria-hidden="true"></i>')),
    ('fa-sign-language', mark_safe('<i class="fa fa-sign-language" aria-hidden="true"></i>')),
    ('fa-signing', mark_safe('<i class="fa fa-signing" aria-hidden="true"></i>')),
    ('fa-tty', mark_safe('<i class="fa fa-tty" aria-hidden="true"></i>')),
    ('fa-universal-access', mark_safe('<i class="fa fa-universal-access" aria-hidden="true"></i>')),
    ('fa-volume-control-phone', mark_safe('<i class="fa fa-volume-control-phone" aria-hidden="true"></i>')),
    ('fa-wheelchair', mark_safe('<i class="fa fa-wheelchair" aria-hidden="true"></i>')),
    ('fa-wheelchair-alt', mark_safe('<i class="fa fa-wheelchair-alt" aria-hidden="true"></i>')),
    ('fa-hand-grab-o', mark_safe('<i class="fa fa-hand-grab-o" aria-hidden="true"></i>')),
    ('fa-hand-lizard-o', mark_safe('<i class="fa fa-hand-lizard-o" aria-hidden="true"></i>')),
    ('fa-hand-o-down', mark_safe('<i class="fa fa-hand-o-down" aria-hidden="true"></i>')),
    ('fa-hand-o-left', mark_safe('<i class="fa fa-hand-o-left" aria-hidden="true"></i>')),
    ('fa-hand-o-right', mark_safe('<i class="fa fa-hand-o-right" aria-hidden="true"></i>')),
    ('fa-hand-o-up', mark_safe('<i class="fa fa-hand-o-up" aria-hidden="true"></i>')),
    ('fa-hand-paper-o', mark_safe('<i class="fa fa-hand-paper-o" aria-hidden="true"></i>')),
    ('fa-hand-peace-o', mark_safe('<i class="fa fa-hand-peace-o" aria-hidden="true"></i>')),
    ('fa-hand-pointer-o', mark_safe('<i class="fa fa-hand-pointer-o" aria-hidden="true"></i>')),
    ('fa-hand-rock-o', mark_safe('<i class="fa fa-hand-rock-o" aria-hidden="true"></i>')),
    ('fa-hand-scissors-o', mark_safe('<i class="fa fa-hand-scissors-o" aria-hidden="true"></i>')),
    ('fa-hand-spock-o', mark_safe('<i class="fa fa-hand-spock-o" aria-hidden="true"></i>')),
    ('fa-hand-stop-o', mark_safe('<i class="fa fa-hand-stop-o" aria-hidden="true"></i>')),
    ('fa-thumbs-down', mark_safe('<i class="fa fa-thumbs-down" aria-hidden="true"></i>')),
    ('fa-thumbs-o-down', mark_safe('<i class="fa fa-thumbs-o-down" aria-hidden="true"></i>')),
    ('fa-thumbs-o-up', mark_safe('<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>')),
    ('fa-thumbs-up', mark_safe('<i class="fa fa-thumbs-up" aria-hidden="true"></i>')),
    ('fa-ambulance', mark_safe('<i class="fa fa-ambulance" aria-hidden="true"></i>')),
    ('fa-automobile', mark_safe('<i class="fa fa-automobile" aria-hidden="true"></i>')),
    ('fa-bicycle', mark_safe('<i class="fa fa-bicycle" aria-hidden="true"></i>')),
    ('fa-bus', mark_safe('<i class="fa fa-bus" aria-hidden="true"></i>')),
    ('fa-cab', mark_safe('<i class="fa fa-cab" aria-hidden="true"></i>')),
    ('fa-car', mark_safe('<i class="fa fa-car" aria-hidden="true"></i>')),
    ('fa-fighter-jet', mark_safe('<i class="fa fa-fighter-jet" aria-hidden="true"></i>')),
    ('fa-motorcycle', mark_safe('<i class="fa fa-motorcycle" aria-hidden="true"></i>')),
    ('fa-plane', mark_safe('<i class="fa fa-plane" aria-hidden="true"></i>')),
    ('fa-rocket', mark_safe('<i class="fa fa-rocket" aria-hidden="true"></i>')),
    ('fa-ship', mark_safe('<i class="fa fa-ship" aria-hidden="true"></i>')),
    ('fa-space-shuttle', mark_safe('<i class="fa fa-space-shuttle" aria-hidden="true"></i>')),
    ('fa-subway', mark_safe('<i class="fa fa-subway" aria-hidden="true"></i>')),
    ('fa-taxi', mark_safe('<i class="fa fa-taxi" aria-hidden="true"></i>')),
    ('fa-train', mark_safe('<i class="fa fa-train" aria-hidden="true"></i>')),
    ('fa-truck', mark_safe('<i class="fa fa-truck" aria-hidden="true"></i>')),
    ('fa-wheelchair', mark_safe('<i class="fa fa-wheelchair" aria-hidden="true"></i>')),
    ('fa-wheelchair-alt', mark_safe('<i class="fa fa-wheelchair-alt" aria-hidden="true"></i>')),
    ('fa-genderless', mark_safe('<i class="fa fa-genderless" aria-hidden="true"></i>')),
    ('fa-intersex', mark_safe('<i class="fa fa-intersex" aria-hidden="true"></i>')),
    ('fa-mars', mark_safe('<i class="fa fa-mars" aria-hidden="true"></i>')),
    ('fa-mars-double', mark_safe('<i class="fa fa-mars-double" aria-hidden="true"></i>')),
    ('fa-mars-stroke', mark_safe('<i class="fa fa-mars-stroke" aria-hidden="true"></i>')),
    ('fa-mars-stroke-h', mark_safe('<i class="fa fa-mars-stroke-h" aria-hidden="true"></i>')),
    ('fa-mars-stroke-v', mark_safe('<i class="fa fa-mars-stroke-v" aria-hidden="true"></i>')),
    ('fa-mercury', mark_safe('<i class="fa fa-mercury" aria-hidden="true"></i>')),
    ('fa-neuter', mark_safe('<i class="fa fa-neuter" aria-hidden="true"></i>')),
    ('fa-transgender', mark_safe('<i class="fa fa-transgender" aria-hidden="true"></i>')),
    ('fa-transgender-alt', mark_safe('<i class="fa fa-transgender-alt" aria-hidden="true"></i>')),
    ('fa-venus', mark_safe('<i class="fa fa-venus" aria-hidden="true"></i>')),
    ('fa-venus-double', mark_safe('<i class="fa fa-venus-double" aria-hidden="true"></i>')),
    ('fa-venus-mars', mark_safe('<i class="fa fa-venus-mars" aria-hidden="true"></i>')),
    ('fa-file', mark_safe('<i class="fa fa-file" aria-hidden="true"></i>')),
    ('fa-file-archive-o', mark_safe('<i class="fa fa-file-archive-o" aria-hidden="true"></i>')),
    ('fa-file-audio-o', mark_safe('<i class="fa fa-file-audio-o" aria-hidden="true"></i>')),
    ('fa-file-code-o', mark_safe('<i class="fa fa-file-code-o" aria-hidden="true"></i>')),
    ('fa-file-excel-o', mark_safe('<i class="fa fa-file-excel-o" aria-hidden="true"></i>')),
    ('fa-file-image-o', mark_safe('<i class="fa fa-file-image-o" aria-hidden="true"></i>')),
    ('fa-file-movie-o', mark_safe('<i class="fa fa-file-movie-o" aria-hidden="true"></i>')),
    ('fa-file-o', mark_safe('<i class="fa fa-file-o" aria-hidden="true"></i>')),
    ('fa-file-pdf-o', mark_safe('<i class="fa fa-file-pdf-o" aria-hidden="true"></i>')),
    ('fa-file-photo-o', mark_safe('<i class="fa fa-file-photo-o" aria-hidden="true"></i>')),
    ('fa-file-picture-o', mark_safe('<i class="fa fa-file-picture-o" aria-hidden="true"></i>')),
    ('fa-file-powerpoint-o', mark_safe('<i class="fa fa-file-powerpoint-o" aria-hidden="true"></i>')),
    ('fa-file-sound-o', mark_safe('<i class="fa fa-file-sound-o" aria-hidden="true"></i>')),
    ('fa-file-text', mark_safe('<i class="fa fa-file-text" aria-hidden="true"></i>')),
    ('fa-file-text-o', mark_safe('<i class="fa fa-file-text-o" aria-hidden="true"></i>')),
    ('fa-file-video-o', mark_safe('<i class="fa fa-file-video-o" aria-hidden="true"></i>')),
    ('fa-file-word-o', mark_safe('<i class="fa fa-file-word-o" aria-hidden="true"></i>')),
    ('fa-file-zip-o', mark_safe('<i class="fa fa-file-zip-o" aria-hidden="true"></i>')),
    ('fa-circle-o-notch', mark_safe('<i class="fa fa-circle-o-notch" aria-hidden="true"></i>')),
    ('fa-cog', mark_safe('<i class="fa fa-cog" aria-hidden="true"></i>')),
    ('fa-gear', mark_safe('<i class="fa fa-gear" aria-hidden="true"></i>')),
    ('fa-refresh', mark_safe('<i class="fa fa-refresh" aria-hidden="true"></i>')),
    ('fa-spinner', mark_safe('<i class="fa fa-spinner" aria-hidden="true"></i>')),
    ('fa-check-square', mark_safe('<i class="fa fa-check-square" aria-hidden="true"></i>')),
    ('fa-check-square-o', mark_safe('<i class="fa fa-check-square-o" aria-hidden="true"></i>')),
    ('fa-circle', mark_safe('<i class="fa fa-circle" aria-hidden="true"></i>')),
    ('fa-circle-o', mark_safe('<i class="fa fa-circle-o" aria-hidden="true"></i>')),
    ('fa-dot-circle-o', mark_safe('<i class="fa fa-dot-circle-o" aria-hidden="true"></i>')),
    ('fa-minus-square', mark_safe('<i class="fa fa-minus-square" aria-hidden="true"></i>')),
    ('fa-minus-square-o', mark_safe('<i class="fa fa-minus-square-o" aria-hidden="true"></i>')),
    ('fa-plus-square', mark_safe('<i class="fa fa-plus-square" aria-hidden="true"></i>')),
    ('fa-plus-square-o', mark_safe('<i class="fa fa-plus-square-o" aria-hidden="true"></i>')),
    ('fa-square', mark_safe('<i class="fa fa-square" aria-hidden="true"></i>')),
    ('fa-square-o', mark_safe('<i class="fa fa-square-o" aria-hidden="true"></i>')),
    ('fa-cc-amex', mark_safe('<i class="fa fa-cc-amex" aria-hidden="true"></i>')),
    ('fa-cc-diners-club', mark_safe('<i class="fa fa-cc-diners-club" aria-hidden="true"></i>')),
    ('fa-cc-discover', mark_safe('<i class="fa fa-cc-discover" aria-hidden="true"></i>')),
    ('fa-cc-jcb', mark_safe('<i class="fa fa-cc-jcb" aria-hidden="true"></i>')),
    ('fa-cc-mastercard', mark_safe('<i class="fa fa-cc-mastercard" aria-hidden="true"></i>')),
    ('fa-cc-paypal', mark_safe('<i class="fa fa-cc-paypal" aria-hidden="true"></i>')),
    ('fa-cc-stripe', mark_safe('<i class="fa fa-cc-stripe" aria-hidden="true"></i>')),
    ('fa-cc-visa', mark_safe('<i class="fa fa-cc-visa" aria-hidden="true"></i>')),
    ('fa-credit-card', mark_safe('<i class="fa fa-credit-card" aria-hidden="true"></i>')),
    ('fa-credit-card-alt', mark_safe('<i class="fa fa-credit-card-alt" aria-hidden="true"></i>')),
    ('fa-google-wallet', mark_safe('<i class="fa fa-google-wallet" aria-hidden="true"></i>')),
    ('fa-paypal', mark_safe('<i class="fa fa-paypal" aria-hidden="true"></i>')),
    ('fa-area-chart', mark_safe('<i class="fa fa-area-chart" aria-hidden="true"></i>')),
    ('fa-bar-chart', mark_safe('<i class="fa fa-bar-chart" aria-hidden="true"></i>')),
    ('fa-bar-chart-o', mark_safe('<i class="fa fa-bar-chart-o" aria-hidden="true"></i>')),
    ('fa-line-chart', mark_safe('<i class="fa fa-line-chart" aria-hidden="true"></i>')),
    ('fa-pie-chart', mark_safe('<i class="fa fa-pie-chart" aria-hidden="true"></i>')),
    ('fa-bitcoin', mark_safe('<i class="fa fa-bitcoin" aria-hidden="true"></i>')),
    ('fa-btc', mark_safe('<i class="fa fa-btc" aria-hidden="true"></i>')),
    ('fa-cny', mark_safe('<i class="fa fa-cny" aria-hidden="true"></i>')),
    ('fa-dollar', mark_safe('<i class="fa fa-dollar" aria-hidden="true"></i>')),
    ('fa-eur', mark_safe('<i class="fa fa-eur" aria-hidden="true"></i>')),
    ('fa-euro', mark_safe('<i class="fa fa-euro" aria-hidden="true"></i>')),
    ('fa-gbp', mark_safe('<i class="fa fa-gbp" aria-hidden="true"></i>')),
    ('fa-gg', mark_safe('<i class="fa fa-gg" aria-hidden="true"></i>')),
    ('fa-gg-circle', mark_safe('<i class="fa fa-gg-circle" aria-hidden="true"></i>')),
    ('fa-ils', mark_safe('<i class="fa fa-ils" aria-hidden="true"></i>')),
    ('fa-inr', mark_safe('<i class="fa fa-inr" aria-hidden="true"></i>')),
    ('fa-jpy', mark_safe('<i class="fa fa-jpy" aria-hidden="true"></i>')),
    ('fa-krw', mark_safe('<i class="fa fa-krw" aria-hidden="true"></i>')),
    ('fa-money', mark_safe('<i class="fa fa-money" aria-hidden="true"></i>')),
    ('fa-rmb', mark_safe('<i class="fa fa-rmb" aria-hidden="true"></i>')),
    ('fa-rouble', mark_safe('<i class="fa fa-rouble" aria-hidden="true"></i>')),
    ('fa-rub', mark_safe('<i class="fa fa-rub" aria-hidden="true"></i>')),
    ('fa-ruble', mark_safe('<i class="fa fa-ruble" aria-hidden="true"></i>')),
    ('fa-rupee', mark_safe('<i class="fa fa-rupee" aria-hidden="true"></i>')),
    ('fa-shekel', mark_safe('<i class="fa fa-shekel" aria-hidden="true"></i>')),
    ('fa-sheqel', mark_safe('<i class="fa fa-sheqel" aria-hidden="true"></i>')),
    ('fa-try', mark_safe('<i class="fa fa-try" aria-hidden="true"></i>')),
    ('fa-turkish-lira', mark_safe('<i class="fa fa-turkish-lira" aria-hidden="true"></i>')),
    ('fa-usd', mark_safe('<i class="fa fa-usd" aria-hidden="true"></i>')),
    ('fa-won', mark_safe('<i class="fa fa-won" aria-hidden="true"></i>')),
    ('fa-yen', mark_safe('<i class="fa fa-yen" aria-hidden="true"></i>')),
    ('fa-align-center', mark_safe('<i class="fa fa-align-center" aria-hidden="true"></i>')),
    ('fa-align-justify', mark_safe('<i class="fa fa-align-justify" aria-hidden="true"></i>')),
    ('fa-align-left', mark_safe('<i class="fa fa-align-left" aria-hidden="true"></i>')),
    ('fa-align-right', mark_safe('<i class="fa fa-align-right" aria-hidden="true"></i>')),
    ('fa-bold', mark_safe('<i class="fa fa-bold" aria-hidden="true"></i>')),
    ('fa-chain', mark_safe('<i class="fa fa-chain" aria-hidden="true"></i>')),
    ('fa-chain-broken', mark_safe('<i class="fa fa-chain-broken" aria-hidden="true"></i>')),
    ('fa-clipboard', mark_safe('<i class="fa fa-clipboard" aria-hidden="true"></i>')),
    ('fa-columns', mark_safe('<i class="fa fa-columns" aria-hidden="true"></i>')),
    ('fa-copy', mark_safe('<i class="fa fa-copy" aria-hidden="true"></i>')),
    ('fa-cut', mark_safe('<i class="fa fa-cut" aria-hidden="true"></i>')),
    ('fa-dedent', mark_safe('<i class="fa fa-dedent" aria-hidden="true"></i>')),
    ('fa-eraser', mark_safe('<i class="fa fa-eraser" aria-hidden="true"></i>')),
    ('fa-file', mark_safe('<i class="fa fa-file" aria-hidden="true"></i>')),
    ('fa-file-o', mark_safe('<i class="fa fa-file-o" aria-hidden="true"></i>')),
    ('fa-file-text', mark_safe('<i class="fa fa-file-text" aria-hidden="true"></i>')),
    ('fa-file-text-o', mark_safe('<i class="fa fa-file-text-o" aria-hidden="true"></i>')),
    ('fa-files-o', mark_safe('<i class="fa fa-files-o" aria-hidden="true"></i>')),
    ('fa-floppy-o', mark_safe('<i class="fa fa-floppy-o" aria-hidden="true"></i>')),
    ('fa-font', mark_safe('<i class="fa fa-font" aria-hidden="true"></i>')),
    ('fa-header', mark_safe('<i class="fa fa-header" aria-hidden="true"></i>')),
    ('fa-indent', mark_safe('<i class="fa fa-indent" aria-hidden="true"></i>')),
    ('fa-italic', mark_safe('<i class="fa fa-italic" aria-hidden="true"></i>')),
    ('fa-link', mark_safe('<i class="fa fa-link" aria-hidden="true"></i>')),
    ('fa-list', mark_safe('<i class="fa fa-list" aria-hidden="true"></i>')),
    ('fa-list-alt', mark_safe('<i class="fa fa-list-alt" aria-hidden="true"></i>')),
    ('fa-list-ol', mark_safe('<i class="fa fa-list-ol" aria-hidden="true"></i>')),
    ('fa-list-ul', mark_safe('<i class="fa fa-list-ul" aria-hidden="true"></i>')),
    ('fa-outdent', mark_safe('<i class="fa fa-outdent" aria-hidden="true"></i>')),
    ('fa-paperclip', mark_safe('<i class="fa fa-paperclip" aria-hidden="true"></i>')),
    ('fa-paragraph', mark_safe('<i class="fa fa-paragraph" aria-hidden="true"></i>')),
    ('fa-paste', mark_safe('<i class="fa fa-paste" aria-hidden="true"></i>')),
    ('fa-repeat', mark_safe('<i class="fa fa-repeat" aria-hidden="true"></i>')),
    ('fa-rotate-left', mark_safe('<i class="fa fa-rotate-left" aria-hidden="true"></i>')),
    ('fa-rotate-right', mark_safe('<i class="fa fa-rotate-right" aria-hidden="true"></i>')),
    ('fa-save', mark_safe('<i class="fa fa-save" aria-hidden="true"></i>')),
    ('fa-scissors', mark_safe('<i class="fa fa-scissors" aria-hidden="true"></i>')),
    ('fa-strikethrough', mark_safe('<i class="fa fa-strikethrough" aria-hidden="true"></i>')),
    ('fa-subscript', mark_safe('<i class="fa fa-subscript" aria-hidden="true"></i>')),
    ('fa-superscript', mark_safe('<i class="fa fa-superscript" aria-hidden="true"></i>')),
    ('fa-table', mark_safe('<i class="fa fa-table" aria-hidden="true"></i>')),
    ('fa-text-height', mark_safe('<i class="fa fa-text-height" aria-hidden="true"></i>')),
    ('fa-text-width', mark_safe('<i class="fa fa-text-width" aria-hidden="true"></i>')),
    ('fa-th', mark_safe('<i class="fa fa-th" aria-hidden="true"></i>')),
    ('fa-th-large', mark_safe('<i class="fa fa-th-large" aria-hidden="true"></i>')),
    ('fa-th-list', mark_safe('<i class="fa fa-th-list" aria-hidden="true"></i>')),
    ('fa-underline', mark_safe('<i class="fa fa-underline" aria-hidden="true"></i>')),
    ('fa-undo', mark_safe('<i class="fa fa-undo" aria-hidden="true"></i>')),
    ('fa-unlink', mark_safe('<i class="fa fa-unlink" aria-hidden="true"></i>')),
    ('fa-angle-double-down', mark_safe('<i class="fa fa-angle-double-down" aria-hidden="true"></i>')),
    ('fa-angle-double-left', mark_safe('<i class="fa fa-angle-double-left" aria-hidden="true"></i>')),
    ('fa-angle-double-right', mark_safe('<i class="fa fa-angle-double-right" aria-hidden="true"></i>')),
    ('fa-angle-double-up', mark_safe('<i class="fa fa-angle-double-up" aria-hidden="true"></i>')),
    ('fa-angle-down', mark_safe('<i class="fa fa-angle-down" aria-hidden="true"></i>')),
    ('fa-angle-left', mark_safe('<i class="fa fa-angle-left" aria-hidden="true"></i>')),
    ('fa-angle-right', mark_safe('<i class="fa fa-angle-right" aria-hidden="true"></i>')),
    ('fa-angle-up', mark_safe('<i class="fa fa-angle-up" aria-hidden="true"></i>')),
    ('fa-arrow-circle-down', mark_safe('<i class="fa fa-arrow-circle-down" aria-hidden="true"></i>')),
    ('fa-arrow-circle-left', mark_safe('<i class="fa fa-arrow-circle-left" aria-hidden="true"></i>')),
    ('fa-arrow-circle-o-down', mark_safe('<i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i>')),
    ('fa-arrow-circle-o-left', mark_safe('<i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i>')),
    ('fa-arrow-circle-o-right', mark_safe('<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>')),
    ('fa-arrow-circle-o-up', mark_safe('<i class="fa fa-arrow-circle-o-up" aria-hidden="true"></i>')),
    ('fa-arrow-circle-right', mark_safe('<i class="fa fa-arrow-circle-right" aria-hidden="true"></i>')),
    ('fa-arrow-circle-up', mark_safe('<i class="fa fa-arrow-circle-up" aria-hidden="true"></i>')),
    ('fa-arrow-down', mark_safe('<i class="fa fa-arrow-down" aria-hidden="true"></i>')),
    ('fa-arrow-left', mark_safe('<i class="fa fa-arrow-left" aria-hidden="true"></i>')),
    ('fa-arrow-right', mark_safe('<i class="fa fa-arrow-right" aria-hidden="true"></i>')),
    ('fa-arrow-up', mark_safe('<i class="fa fa-arrow-up" aria-hidden="true"></i>')),
    ('fa-arrows', mark_safe('<i class="fa fa-arrows" aria-hidden="true"></i>')),
    ('fa-arrows-alt', mark_safe('<i class="fa fa-arrows-alt" aria-hidden="true"></i>')),
    ('fa-arrows-h', mark_safe('<i class="fa fa-arrows-h" aria-hidden="true"></i>')),
    ('fa-arrows-v', mark_safe('<i class="fa fa-arrows-v" aria-hidden="true"></i>')),
    ('fa-caret-down', mark_safe('<i class="fa fa-caret-down" aria-hidden="true"></i>')),
    ('fa-caret-left', mark_safe('<i class="fa fa-caret-left" aria-hidden="true"></i>')),
    ('fa-caret-right', mark_safe('<i class="fa fa-caret-right" aria-hidden="true"></i>')),
    ('fa-caret-square-o-down', mark_safe('<i class="fa fa-caret-square-o-down" aria-hidden="true"></i>')),
    ('fa-caret-square-o-left', mark_safe('<i class="fa fa-caret-square-o-left" aria-hidden="true"></i>')),
    ('fa-caret-square-o-right', mark_safe('<i class="fa fa-caret-square-o-right" aria-hidden="true"></i>')),
    ('fa-caret-square-o-up', mark_safe('<i class="fa fa-caret-square-o-up" aria-hidden="true"></i>')),
    ('fa-caret-up', mark_safe('<i class="fa fa-caret-up" aria-hidden="true"></i>')),
    ('fa-chevron-circle-down', mark_safe('<i class="fa fa-chevron-circle-down" aria-hidden="true"></i>')),
    ('fa-chevron-circle-left', mark_safe('<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>')),
    ('fa-chevron-circle-right', mark_safe('<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>')),
    ('fa-chevron-circle-up', mark_safe('<i class="fa fa-chevron-circle-up" aria-hidden="true"></i>')),
    ('fa-chevron-down', mark_safe('<i class="fa fa-chevron-down" aria-hidden="true"></i>')),
    ('fa-chevron-left', mark_safe('<i class="fa fa-chevron-left" aria-hidden="true"></i>')),
    ('fa-chevron-right', mark_safe('<i class="fa fa-chevron-right" aria-hidden="true"></i>')),
    ('fa-chevron-up', mark_safe('<i class="fa fa-chevron-up" aria-hidden="true"></i>')),
    ('fa-exchange', mark_safe('<i class="fa fa-exchange" aria-hidden="true"></i>')),
    ('fa-hand-o-down', mark_safe('<i class="fa fa-hand-o-down" aria-hidden="true"></i>')),
    ('fa-hand-o-left', mark_safe('<i class="fa fa-hand-o-left" aria-hidden="true"></i>')),
    ('fa-hand-o-right', mark_safe('<i class="fa fa-hand-o-right" aria-hidden="true"></i>')),
    ('fa-hand-o-up', mark_safe('<i class="fa fa-hand-o-up" aria-hidden="true"></i>')),
    ('fa-long-arrow-down', mark_safe('<i class="fa fa-long-arrow-down" aria-hidden="true"></i>')),
    ('fa-long-arrow-left', mark_safe('<i class="fa fa-long-arrow-left" aria-hidden="true"></i>')),
    ('fa-long-arrow-right', mark_safe('<i class="fa fa-long-arrow-right" aria-hidden="true"></i>')),
    ('fa-long-arrow-up', mark_safe('<i class="fa fa-long-arrow-up" aria-hidden="true"></i>')),
    ('fa-toggle-down', mark_safe('<i class="fa fa-toggle-down" aria-hidden="true"></i>')),
    ('fa-toggle-left', mark_safe('<i class="fa fa-toggle-left" aria-hidden="true"></i>')),
    ('fa-toggle-right', mark_safe('<i class="fa fa-toggle-right" aria-hidden="true"></i>')),
    ('fa-toggle-up', mark_safe('<i class="fa fa-toggle-up" aria-hidden="true"></i>')),
    ('fa-arrows-alt', mark_safe('<i class="fa fa-arrows-alt" aria-hidden="true"></i>')),
    ('fa-backward', mark_safe('<i class="fa fa-backward" aria-hidden="true"></i>')),
    ('fa-compress', mark_safe('<i class="fa fa-compress" aria-hidden="true"></i>')),
    ('fa-eject', mark_safe('<i class="fa fa-eject" aria-hidden="true"></i>')),
    ('fa-expand', mark_safe('<i class="fa fa-expand" aria-hidden="true"></i>')),
    ('fa-fast-backward', mark_safe('<i class="fa fa-fast-backward" aria-hidden="true"></i>')),
    ('fa-fast-forward', mark_safe('<i class="fa fa-fast-forward" aria-hidden="true"></i>')),
    ('fa-forward', mark_safe('<i class="fa fa-forward" aria-hidden="true"></i>')),
    ('fa-pause', mark_safe('<i class="fa fa-pause" aria-hidden="true"></i>')),
    ('fa-pause-circle', mark_safe('<i class="fa fa-pause-circle" aria-hidden="true"></i>')),
    ('fa-pause-circle-o', mark_safe('<i class="fa fa-pause-circle-o" aria-hidden="true"></i>')),
    ('fa-play', mark_safe('<i class="fa fa-play" aria-hidden="true"></i>')),
    ('fa-play-circle', mark_safe('<i class="fa fa-play-circle" aria-hidden="true"></i>')),
    ('fa-play-circle-o', mark_safe('<i class="fa fa-play-circle-o" aria-hidden="true"></i>')),
    ('fa-random', mark_safe('<i class="fa fa-random" aria-hidden="true"></i>')),
    ('fa-step-backward', mark_safe('<i class="fa fa-step-backward" aria-hidden="true"></i>')),
    ('fa-step-forward', mark_safe('<i class="fa fa-step-forward" aria-hidden="true"></i>')),
    ('fa-stop', mark_safe('<i class="fa fa-stop" aria-hidden="true"></i>')),
    ('fa-stop-circle', mark_safe('<i class="fa fa-stop-circle" aria-hidden="true"></i>')),
    ('fa-stop-circle-o', mark_safe('<i class="fa fa-stop-circle-o" aria-hidden="true"></i>')),
    ('fa-youtube-play', mark_safe('<i class="fa fa-youtube-play" aria-hidden="true"></i>')),
    ('fa-500px', mark_safe('<i class="fa fa-500px" aria-hidden="true"></i>')),
    ('fa-adn', mark_safe('<i class="fa fa-adn" aria-hidden="true"></i>')),
    ('fa-amazon', mark_safe('<i class="fa fa-amazon" aria-hidden="true"></i>')),
    ('fa-android', mark_safe('<i class="fa fa-android" aria-hidden="true"></i>')),
    ('fa-angellist', mark_safe('<i class="fa fa-angellist" aria-hidden="true"></i>')),
    ('fa-apple', mark_safe('<i class="fa fa-apple" aria-hidden="true"></i>')),
    ('fa-bandcamp', mark_safe('<i class="fa fa-bandcamp" aria-hidden="true"></i>')),
    ('fa-behance', mark_safe('<i class="fa fa-behance" aria-hidden="true"></i>')),
    ('fa-behance-square', mark_safe('<i class="fa fa-behance-square" aria-hidden="true"></i>')),
    ('fa-bitbucket', mark_safe('<i class="fa fa-bitbucket" aria-hidden="true"></i>')),
    ('fa-bitbucket-square', mark_safe('<i class="fa fa-bitbucket-square" aria-hidden="true"></i>')),
    ('fa-bitcoin', mark_safe('<i class="fa fa-bitcoin" aria-hidden="true"></i>')),
    ('fa-black-tie', mark_safe('<i class="fa fa-black-tie" aria-hidden="true"></i>')),
    ('fa-bluetooth', mark_safe('<i class="fa fa-bluetooth" aria-hidden="true"></i>')),
    ('fa-bluetooth-b', mark_safe('<i class="fa fa-bluetooth-b" aria-hidden="true"></i>')),
    ('fa-btc', mark_safe('<i class="fa fa-btc" aria-hidden="true"></i>')),
    ('fa-buysellads', mark_safe('<i class="fa fa-buysellads" aria-hidden="true"></i>')),
    ('fa-cc-amex', mark_safe('<i class="fa fa-cc-amex" aria-hidden="true"></i>')),
    ('fa-cc-diners-club', mark_safe('<i class="fa fa-cc-diners-club" aria-hidden="true"></i>')),
    ('fa-cc-discover', mark_safe('<i class="fa fa-cc-discover" aria-hidden="true"></i>')),
    ('fa-cc-jcb', mark_safe('<i class="fa fa-cc-jcb" aria-hidden="true"></i>')),
    ('fa-cc-mastercard', mark_safe('<i class="fa fa-cc-mastercard" aria-hidden="true"></i>')),
    ('fa-cc-paypal', mark_safe('<i class="fa fa-cc-paypal" aria-hidden="true"></i>')),
    ('fa-cc-stripe', mark_safe('<i class="fa fa-cc-stripe" aria-hidden="true"></i>')),
    ('fa-cc-visa', mark_safe('<i class="fa fa-cc-visa" aria-hidden="true"></i>')),
    ('fa-chrome', mark_safe('<i class="fa fa-chrome" aria-hidden="true"></i>')),
    ('fa-codepen', mark_safe('<i class="fa fa-codepen" aria-hidden="true"></i>')),
    ('fa-codiepie', mark_safe('<i class="fa fa-codiepie" aria-hidden="true"></i>')),
    ('fa-connectdevelop', mark_safe('<i class="fa fa-connectdevelop" aria-hidden="true"></i>')),
    ('fa-contao', mark_safe('<i class="fa fa-contao" aria-hidden="true"></i>')),
    ('fa-css3', mark_safe('<i class="fa fa-css3" aria-hidden="true"></i>')),
    ('fa-dashcube', mark_safe('<i class="fa fa-dashcube" aria-hidden="true"></i>')),
    ('fa-delicious', mark_safe('<i class="fa fa-delicious" aria-hidden="true"></i>')),
    ('fa-deviantart', mark_safe('<i class="fa fa-deviantart" aria-hidden="true"></i>')),
    ('fa-digg', mark_safe('<i class="fa fa-digg" aria-hidden="true"></i>')),
    ('fa-dribbble', mark_safe('<i class="fa fa-dribbble" aria-hidden="true"></i>')),
    ('fa-dropbox', mark_safe('<i class="fa fa-dropbox" aria-hidden="true"></i>')),
    ('fa-drupal', mark_safe('<i class="fa fa-drupal" aria-hidden="true"></i>')),
    ('fa-edge', mark_safe('<i class="fa fa-edge" aria-hidden="true"></i>')),
    ('fa-eercast', mark_safe('<i class="fa fa-eercast" aria-hidden="true"></i>')),
    ('fa-empire', mark_safe('<i class="fa fa-empire" aria-hidden="true"></i>')),
    ('fa-envira', mark_safe('<i class="fa fa-envira" aria-hidden="true"></i>')),
    ('fa-etsy', mark_safe('<i class="fa fa-etsy" aria-hidden="true"></i>')),
    ('fa-expeditedssl', mark_safe('<i class="fa fa-expeditedssl" aria-hidden="true"></i>')),
    ('fa-fa', mark_safe('<i class="fa fa-fa" aria-hidden="true"></i>')),
    ('fa-facebook', mark_safe('<i class="fa fa-facebook" aria-hidden="true"></i>')),
    ('fa-facebook-f', mark_safe('<i class="fa fa-facebook-f" aria-hidden="true"></i>')),
    ('fa-facebook-official', mark_safe('<i class="fa fa-facebook-official" aria-hidden="true"></i>')),
    ('fa-facebook-square', mark_safe('<i class="fa fa-facebook-square" aria-hidden="true"></i>')),
    ('fa-firefox', mark_safe('<i class="fa fa-firefox" aria-hidden="true"></i>')),
    ('fa-first-order', mark_safe('<i class="fa fa-first-order" aria-hidden="true"></i>')),
    ('fa-flickr', mark_safe('<i class="fa fa-flickr" aria-hidden="true"></i>')),
    ('fa-font-awesome', mark_safe('<i class="fa fa-font-awesome" aria-hidden="true"></i>')),
    ('fa-fonticons', mark_safe('<i class="fa fa-fonticons" aria-hidden="true"></i>')),
    ('fa-fort-awesome', mark_safe('<i class="fa fa-fort-awesome" aria-hidden="true"></i>')),
    ('fa-forumbee', mark_safe('<i class="fa fa-forumbee" aria-hidden="true"></i>')),
    ('fa-foursquare', mark_safe('<i class="fa fa-foursquare" aria-hidden="true"></i>')),
    ('fa-free-code-camp', mark_safe('<i class="fa fa-free-code-camp" aria-hidden="true"></i>')),
    ('fa-ge', mark_safe('<i class="fa fa-ge" aria-hidden="true"></i>')),
    ('fa-get-pocket', mark_safe('<i class="fa fa-get-pocket" aria-hidden="true"></i>')),
    ('fa-gg', mark_safe('<i class="fa fa-gg" aria-hidden="true"></i>')),
    ('fa-gg-circle', mark_safe('<i class="fa fa-gg-circle" aria-hidden="true"></i>')),
    ('fa-git', mark_safe('<i class="fa fa-git" aria-hidden="true"></i>')),
    ('fa-git-square', mark_safe('<i class="fa fa-git-square" aria-hidden="true"></i>')),
    ('fa-github', mark_safe('<i class="fa fa-github" aria-hidden="true"></i>')),
    ('fa-github-alt', mark_safe('<i class="fa fa-github-alt" aria-hidden="true"></i>')),
    ('fa-github-square', mark_safe('<i class="fa fa-github-square" aria-hidden="true"></i>')),
    ('fa-gitlab', mark_safe('<i class="fa fa-gitlab" aria-hidden="true"></i>')),
    ('fa-gittip', mark_safe('<i class="fa fa-gittip" aria-hidden="true"></i>')),
    ('fa-glide', mark_safe('<i class="fa fa-glide" aria-hidden="true"></i>')),
    ('fa-glide-g', mark_safe('<i class="fa fa-glide-g" aria-hidden="true"></i>')),
    ('fa-google', mark_safe('<i class="fa fa-google" aria-hidden="true"></i>')),
    ('fa-google-plus', mark_safe('<i class="fa fa-google-plus" aria-hidden="true"></i>')),
    ('fa-google-plus-circle', mark_safe('<i class="fa fa-google-plus-circle" aria-hidden="true"></i>')),
    ('fa-google-plus-official', mark_safe('<i class="fa fa-google-plus-official" aria-hidden="true"></i>')),
    ('fa-google-plus-square', mark_safe('<i class="fa fa-google-plus-square" aria-hidden="true"></i>')),
    ('fa-google-wallet', mark_safe('<i class="fa fa-google-wallet" aria-hidden="true"></i>')),
    ('fa-gratipay', mark_safe('<i class="fa fa-gratipay" aria-hidden="true"></i>')),
    ('fa-grav', mark_safe('<i class="fa fa-grav" aria-hidden="true"></i>')),
    ('fa-hacker-news', mark_safe('<i class="fa fa-hacker-news" aria-hidden="true"></i>')),
    ('fa-houzz', mark_safe('<i class="fa fa-houzz" aria-hidden="true"></i>')),
    ('fa-html5', mark_safe('<i class="fa fa-html5" aria-hidden="true"></i>')),
    ('fa-imdb', mark_safe('<i class="fa fa-imdb" aria-hidden="true"></i>')),
    ('fa-instagram', mark_safe('<i class="fa fa-instagram" aria-hidden="true"></i>')),
    ('fa-internet-explorer', mark_safe('<i class="fa fa-internet-explorer" aria-hidden="true"></i>')),
    ('fa-ioxhost', mark_safe('<i class="fa fa-ioxhost" aria-hidden="true"></i>')),
    ('fa-joomla', mark_safe('<i class="fa fa-joomla" aria-hidden="true"></i>')),
    ('fa-jsfiddle', mark_safe('<i class="fa fa-jsfiddle" aria-hidden="true"></i>')),
    ('fa-lastfm', mark_safe('<i class="fa fa-lastfm" aria-hidden="true"></i>')),
    ('fa-lastfm-square', mark_safe('<i class="fa fa-lastfm-square" aria-hidden="true"></i>')),
    ('fa-leanpub', mark_safe('<i class="fa fa-leanpub" aria-hidden="true"></i>')),
    ('fa-linkedin', mark_safe('<i class="fa fa-linkedin" aria-hidden="true"></i>')),
    ('fa-linkedin-square', mark_safe('<i class="fa fa-linkedin-square" aria-hidden="true"></i>')),
    ('fa-linode', mark_safe('<i class="fa fa-linode" aria-hidden="true"></i>')),
    ('fa-linux', mark_safe('<i class="fa fa-linux" aria-hidden="true"></i>')),
    ('fa-maxcdn', mark_safe('<i class="fa fa-maxcdn" aria-hidden="true"></i>')),
    ('fa-meanpath', mark_safe('<i class="fa fa-meanpath" aria-hidden="true"></i>')),
    ('fa-medium', mark_safe('<i class="fa fa-medium" aria-hidden="true"></i>')),
    ('fa-meetup', mark_safe('<i class="fa fa-meetup" aria-hidden="true"></i>')),
    ('fa-mixcloud', mark_safe('<i class="fa fa-mixcloud" aria-hidden="true"></i>')),
    ('fa-modx', mark_safe('<i class="fa fa-modx" aria-hidden="true"></i>')),
    ('fa-odnoklassniki', mark_safe('<i class="fa fa-odnoklassniki" aria-hidden="true"></i>')),
    ('fa-odnoklassniki-square', mark_safe('<i class="fa fa-odnoklassniki-square" aria-hidden="true"></i>')),
    ('fa-opencart', mark_safe('<i class="fa fa-opencart" aria-hidden="true"></i>')),
    ('fa-openid', mark_safe('<i class="fa fa-openid" aria-hidden="true"></i>')),
    ('fa-opera', mark_safe('<i class="fa fa-opera" aria-hidden="true"></i>')),
    ('fa-optin-monster', mark_safe('<i class="fa fa-optin-monster" aria-hidden="true"></i>')),
    ('fa-pagelines', mark_safe('<i class="fa fa-pagelines" aria-hidden="true"></i>')),
    ('fa-paypal', mark_safe('<i class="fa fa-paypal" aria-hidden="true"></i>')),
    ('fa-pied-piper', mark_safe('<i class="fa fa-pied-piper" aria-hidden="true"></i>')),
    ('fa-pied-piper-alt', mark_safe('<i class="fa fa-pied-piper-alt" aria-hidden="true"></i>')),
    ('fa-pied-piper-pp', mark_safe('<i class="fa fa-pied-piper-pp" aria-hidden="true"></i>')),
    ('fa-pinterest', mark_safe('<i class="fa fa-pinterest" aria-hidden="true"></i>')),
    ('fa-pinterest-p', mark_safe('<i class="fa fa-pinterest-p" aria-hidden="true"></i>')),
    ('fa-pinterest-square', mark_safe('<i class="fa fa-pinterest-square" aria-hidden="true"></i>')),
    ('fa-product-hunt', mark_safe('<i class="fa fa-product-hunt" aria-hidden="true"></i>')),
    ('fa-qq', mark_safe('<i class="fa fa-qq" aria-hidden="true"></i>')),
    ('fa-quora', mark_safe('<i class="fa fa-quora" aria-hidden="true"></i>')),
    ('fa-ra', mark_safe('<i class="fa fa-ra" aria-hidden="true"></i>')),
    ('fa-ravelry', mark_safe('<i class="fa fa-ravelry" aria-hidden="true"></i>')),
    ('fa-rebel', mark_safe('<i class="fa fa-rebel" aria-hidden="true"></i>')),
    ('fa-reddit', mark_safe('<i class="fa fa-reddit" aria-hidden="true"></i>')),
    ('fa-reddit-alien', mark_safe('<i class="fa fa-reddit-alien" aria-hidden="true"></i>')),
    ('fa-reddit-square', mark_safe('<i class="fa fa-reddit-square" aria-hidden="true"></i>')),
    ('fa-renren', mark_safe('<i class="fa fa-renren" aria-hidden="true"></i>')),
    ('fa-resistance', mark_safe('<i class="fa fa-resistance" aria-hidden="true"></i>')),
    ('fa-safari', mark_safe('<i class="fa fa-safari" aria-hidden="true"></i>')),
    ('fa-scribd', mark_safe('<i class="fa fa-scribd" aria-hidden="true"></i>')),
    ('fa-sellsy', mark_safe('<i class="fa fa-sellsy" aria-hidden="true"></i>')),
    ('fa-share-alt', mark_safe('<i class="fa fa-share-alt" aria-hidden="true"></i>')),
    ('fa-share-alt-square', mark_safe('<i class="fa fa-share-alt-square" aria-hidden="true"></i>')),
    ('fa-shirtsinbulk', mark_safe('<i class="fa fa-shirtsinbulk" aria-hidden="true"></i>')),
    ('fa-simplybuilt', mark_safe('<i class="fa fa-simplybuilt" aria-hidden="true"></i>')),
    ('fa-skyatlas', mark_safe('<i class="fa fa-skyatlas" aria-hidden="true"></i>')),
    ('fa-skype', mark_safe('<i class="fa fa-skype" aria-hidden="true"></i>')),
    ('fa-slack', mark_safe('<i class="fa fa-slack" aria-hidden="true"></i>')),
    ('fa-slideshare', mark_safe('<i class="fa fa-slideshare" aria-hidden="true"></i>')),
    ('fa-snapchat', mark_safe('<i class="fa fa-snapchat" aria-hidden="true"></i>')),
    ('fa-snapchat-ghost', mark_safe('<i class="fa fa-snapchat-ghost" aria-hidden="true"></i>')),
    ('fa-snapchat-square', mark_safe('<i class="fa fa-snapchat-square" aria-hidden="true"></i>')),
    ('fa-soundcloud', mark_safe('<i class="fa fa-soundcloud" aria-hidden="true"></i>')),
    ('fa-spotify', mark_safe('<i class="fa fa-spotify" aria-hidden="true"></i>')),
    ('fa-stack-exchange', mark_safe('<i class="fa fa-stack-exchange" aria-hidden="true"></i>')),
    ('fa-stack-overflow', mark_safe('<i class="fa fa-stack-overflow" aria-hidden="true"></i>')),
    ('fa-steam', mark_safe('<i class="fa fa-steam" aria-hidden="true"></i>')),
    ('fa-steam-square', mark_safe('<i class="fa fa-steam-square" aria-hidden="true"></i>')),
    ('fa-stumbleupon', mark_safe('<i class="fa fa-stumbleupon" aria-hidden="true"></i>')),
    ('fa-stumbleupon-circle', mark_safe('<i class="fa fa-stumbleupon-circle" aria-hidden="true"></i>')),
    ('fa-superpowers', mark_safe('<i class="fa fa-superpowers" aria-hidden="true"></i>')),
    ('fa-telegram', mark_safe('<i class="fa fa-telegram" aria-hidden="true"></i>')),
    ('fa-themeisle', mark_safe('<i class="fa fa-themeisle" aria-hidden="true"></i>')),
    ('fa-trello', mark_safe('<i class="fa fa-trello" aria-hidden="true"></i>')),
    ('fa-tripadvisor', mark_safe('<i class="fa fa-tripadvisor" aria-hidden="true"></i>')),
    ('fa-tumblr', mark_safe('<i class="fa fa-tumblr" aria-hidden="true"></i>')),
    ('fa-tumblr-square', mark_safe('<i class="fa fa-tumblr-square" aria-hidden="true"></i>')),
    ('fa-twitch', mark_safe('<i class="fa fa-twitch" aria-hidden="true"></i>')),
    ('fa-twitter', mark_safe('<i class="fa fa-twitter" aria-hidden="true"></i>')),
    ('fa-twitter-square', mark_safe('<i class="fa fa-twitter-square" aria-hidden="true"></i>')),
    ('fa-usb', mark_safe('<i class="fa fa-usb" aria-hidden="true"></i>')),
    ('fa-viacoin', mark_safe('<i class="fa fa-viacoin" aria-hidden="true"></i>')),
    ('fa-viadeo', mark_safe('<i class="fa fa-viadeo" aria-hidden="true"></i>')),
    ('fa-viadeo-square', mark_safe('<i class="fa fa-viadeo-square" aria-hidden="true"></i>')),
    ('fa-vimeo', mark_safe('<i class="fa fa-vimeo" aria-hidden="true"></i>')),
    ('fa-vimeo-square', mark_safe('<i class="fa fa-vimeo-square" aria-hidden="true"></i>')),
    ('fa-vine', mark_safe('<i class="fa fa-vine" aria-hidden="true"></i>')),
    ('fa-vk', mark_safe('<i class="fa fa-vk" aria-hidden="true"></i>')),
    ('fa-wechat', mark_safe('<i class="fa fa-wechat" aria-hidden="true"></i>')),
    ('fa-whatsapp', mark_safe('<i class="fa fa-whatsapp" aria-hidden="true"></i>')),
    ('fa-wikipedia-w', mark_safe('<i class="fa fa-wikipedia-w" aria-hidden="true"></i>')),
    ('fa-windows', mark_safe('<i class="fa fa-windows" aria-hidden="true"></i>')),
    ('fa-wordpress', mark_safe('<i class="fa fa-wordpress" aria-hidden="true"></i>')),
    ('fa-wpbeginner', mark_safe('<i class="fa fa-wpbeginner" aria-hidden="true"></i>')),
    ('fa-wpexplorer', mark_safe('<i class="fa fa-wpexplorer" aria-hidden="true"></i>')),
    ('fa-wpforms', mark_safe('<i class="fa fa-wpforms" aria-hidden="true"></i>')),
    ('fa-xing', mark_safe('<i class="fa fa-xing" aria-hidden="true"></i>')),
    ('fa-xing-square', mark_safe('<i class="fa fa-xing-square" aria-hidden="true"></i>')),
    ('fa-y-combinator', mark_safe('<i class="fa fa-y-combinator" aria-hidden="true"></i>')),
    ('fa-y-combinator-square', mark_safe('<i class="fa fa-y-combinator-square" aria-hidden="true"></i>')),
    ('fa-yahoo', mark_safe('<i class="fa fa-yahoo" aria-hidden="true"></i>')),
    ('fa-yc', mark_safe('<i class="fa fa-yc" aria-hidden="true"></i>')),
    ('fa-yc-square', mark_safe('<i class="fa fa-yc-square" aria-hidden="true"></i>')),
    ('fa-yelp', mark_safe('<i class="fa fa-yelp" aria-hidden="true"></i>')),
    ('fa-yoast', mark_safe('<i class="fa fa-yoast" aria-hidden="true"></i>')),
    ('fa-youtube', mark_safe('<i class="fa fa-youtube" aria-hidden="true"></i>')),
    ('fa-youtube-play', mark_safe('<i class="fa fa-youtube-play" aria-hidden="true"></i>')),
    ('fa-youtube-square', mark_safe('<i class="fa fa-youtube-square" aria-hidden="true"></i>')),
    ('fa-ambulance', mark_safe('<i class="fa fa-ambulance" aria-hidden="true"></i>')),
    ('fa-h-square', mark_safe('<i class="fa fa-h-square" aria-hidden="true"></i>')),
    ('fa-heart', mark_safe('<i class="fa fa-heart" aria-hidden="true"></i>')),
    ('fa-heart-o', mark_safe('<i class="fa fa-heart-o" aria-hidden="true"></i>')),
    ('fa-heartbeat', mark_safe('<i class="fa fa-heartbeat" aria-hidden="true"></i>')),
    ('fa-hospital-o', mark_safe('<i class="fa fa-hospital-o" aria-hidden="true"></i>')),
    ('fa-medkit', mark_safe('<i class="fa fa-medkit" aria-hidden="true"></i>')),
    ('fa-plus-square', mark_safe('<i class="fa fa-plus-square" aria-hidden="true"></i>')),
    ('fa-stethoscope', mark_safe('<i class="fa fa-stethoscope" aria-hidden="true"></i>')),
    ('fa-user-md', mark_safe('<i class="fa fa-user-md" aria-hidden="true"></i>')),
    ('fa-wheelchair', mark_safe('<i class="fa fa-wheelchair" aria-hidden="true"></i>')),
    ('fa-wheelchair-alt', mark_safe('<i class="fa fa-wheelchair-alt" aria-hidden="true"></i>')),

]


class MenuModelForm(BaseModelForm):
    exclude_bootstrap = ['icon']

    class Meta:
        model = Menu
        fields = '__all__'
        widgets = {
            'icon': forms.RadioSelect(choices=icon_choice)
        }


class SmenuModelForm(BaseModelForm):
    exclude_bootstrap = ['icon']

    # def __init__(self,mobj,*args,**kwargs):
    #     self.mobj = mobj
    #     super(SmenuModelForm, self).__init__(*args,**kwargs)
    #
    # def save(self, commit=True):
    #     self.instance.menu = self.mobj
    #     super(SmenuModelForm, self).save(commit)

    class Meta:
        model = Permission
        fields = ['title', 'url', 'url_name', 'icon']
        widgets = {
            'icon': forms.RadioSelect(choices=icon_choice)
        }


class PmenuModelForm(BaseModelForm):
    # def __init__(self, pobj, *args, **kwargs):
    #     self.pobj = pobj
    #     super(PmenuModelForm, self).__init__(*args, **kwargs)
    #
    # def save(self, commit=True):
    #     self.instance.pid = self.pobj
    #     super(PmenuModelForm, self).save(commit)

    class Meta:
        model = Permission
        fields = ['title', 'url', 'url_name']



class PmenuModelForm(BaseModelForm):
    # def __init__(self, pobj, *args, **kwargs):
    #     self.pobj = pobj
    #     super(PmenuModelForm, self).__init__(*args, **kwargs)
    #
    # def save(self, commit=True):
    #     self.instance.pid = self.pobj
    #     super(PmenuModelForm, self).save(commit)

    class Meta:
        model = Permission
        fields = ['title', 'url', 'url_name']



class MultiAddPermissionForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control"})
    )

    url = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control"})
    )

    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control"})
    )

    menu_id = forms.ChoiceField(
        choices=[None, '-----'],
        widget=forms.Select(attrs={'class': "form-control"}),
        required=False,
    )

    pid_id = forms.ChoiceField(
        choices=[None, '-----'],
        widget=forms.Select(attrs={'class': "form-control"}),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # print(Menu.objects.values_list('id', 'title'),'-----')
        # self.files['menu_id'].choices += Menu.objects.values_list('id', 'title')
        print(self.files['menu_id'].choices,'-----')
        # self.files['pid_id'].choices += Permission.objects.filter(pid__isnull=True).execlude(
            # menu__isnull=True).values_list('id', 'title')

class MultiEditPermissionForm(forms.Form):
    id = forms.IntegerField(
        widget=forms.HiddenInput(),
    )

    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control"})
    )

    url = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control"})
    )

    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control"})
    )

    menu_id = forms.ChoiceField(
        choices=[None, '-----'],
        widget=forms.Select(attrs={'class': "form-control"}),
        required=False,
    )

    pid_id = forms.ChoiceField(
        choices=[None, '-----'],
        widget=forms.Select(attrs={'class': "form-control"}),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super(MultiAddPermissionForm, self).__init__(*args, **kwargs)
        self.files['menu_id'].choices += Menu.objects.values_list('id', 'title')
        self.files['pid_id'].choices += Permission.objects.filter(pid__isnull=True).execlude(
            menu__isnull=True).values_list('id', 'title')