# Generated by Django 3.1.2 on 2021-01-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_memu',
            field=models.BooleanField(default=False, verbose_name='是否是菜单'),
        ),
        migrations.AddField(
            model_name='permission',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='父级菜单'),
        ),
    ]
