# Generated by Django 3.1.3 on 2021-01-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='url_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='URL别名'),
        ),
    ]
