# Generated by Django 3.1.3 on 2021-01-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='URL别名'),
        ),
    ]
