# Generated by Django 3.1.3 on 2021-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20210106_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=32, verbose_name='图标'),
        ),
    ]
